spec: remove backticks and use new logging
cnti-testcatalog/testsuite pull request #1954
Opened 2024-04-08 15:16 UTC by kosstennbl

Replace all backtick command execution with ShellCmd module.
Use Log instead of LOGGING module.
Fix edge-case issues caused by logging refactor.
Remove commented-out code.

Commit looks scary, but most of the code is changed with a couple of regexes, only small amount of collisions that were needed to be resolved manually is present.

## Issues:
REF: #1495

No changes to documentation is needed.
Was tested for successful compilation.
Needs testing with github actions (some of the tests are hard to test on local environments)

2024-04-08 21:03 UTC, martin-mat requested changes

2024-04-08 21:03 UTC, martin-mat commented on spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
> +#     result[:output] = `./cnf-testsuite all ~disk_fill ~pod_delete ~pod_network_latency ~pod_network_corruption ~pod_network_duplication ~pod_io_stress ~pod_memory_hog ~node_drain ~pod_dns_error ~ch
this line does not make any sense to me

2024-04-08 21:03 UTC, martin-mat commented on spec/cnf_testsuite_all/cnf_testsuite_network_chaos_spec.cr
> +  #   result[:status].success?.should be_true
where does the result come from?

2024-04-09 07:13 UTC, HashNuke commented on src/tasks/utils/utils.cr
>      Log.info { "#{log_prefix} command: #{cmd}" }
I would look into using `Log.for("ShellCmd.run").info()`

2024-04-09 07:17 UTC, HashNuke commented
`ShellCmd.run` is more suitable for commands that either output stdout on success or stderr on failure. The stderr is output in the end after the stdout is logged.

* The cnf-testsuite commands could be outputting both due to the nature of the integrations.
* In the logs when looking into issues, it would help to see the output in the same order as the command's output rather than all the stdouts grouped first, followed by all the stderr outputs.

It would be better to use the same variable for collecting both stderr and stdout. That is a case for for a new function separate from `ShellCmd.run`.

2024-04-09 07:58 UTC, kosstennbl commented on spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
> +#     result[:output] = `./cnf-testsuite all ~disk_fill ~pod_delete ~pod_network_latency ~pod_network_corruption ~pod_network_duplication ~pod_io_stress ~pod_memory_hog ~node_drain ~pod_dns_error ~ch
As mentioned in PR message, commented out code is broken in this PR.

I'm not sure that it's reasonable to spend efforts on fixing code that should be deleted anyways, but if it's needed - it could be done.

2024-04-09 07:59 UTC, kosstennbl commented on spec/cnf_testsuite_all/cnf_testsuite_network_chaos_spec.cr
> +  #   result[:status].success?.should be_true
ditto

2024-04-09 08:07 UTC, kosstennbl commented
> `ShellCmd.run` is more suitable for commands that either output stdout on success or stderr on failure. The stderr is output in the end after the stdout is logged.
> 
> * The cnf-testsuite commands could be outputting both due to the nature of the integrations.
> * In the logs when looking into issues, it would help to see the output in the same order as the command's output rather than all the stdouts grouped first, followed by all the stderr outputs.
> 
> It would be better to use the same variable for collecting both stderr and stdout. That is a case for for a new function separate from `ShellCmd.run`.



> `ShellCmd.run` is more suitable for commands that either output stdout on success or stderr on failure. The stderr is output in the end after the stdout is logged.
> 
> * The cnf-testsuite commands could be outputting both due to the nature of the integrations.
> * In the logs when looking into issues, it would help to see the output in the same order as the command's output rather than all the stdouts grouped first, followed by all the stderr outputs.
> 
> It would be better to use the same variable for collecting both stderr and stdout. That is a case for for a new function separate from `ShellCmd.run`.

As we have discussed earlier - agree, that sounds like a nice addition, but I'm not sure that it should be implemented in the scope of this PR.
As these changes for logging and backticks are quite wide and can bring confusion in some places - I'd rather prefer fixing (if needed) and merging this one, and then - creating new PR with addition of second command and using it where needed.

2024-04-09 08:34 UTC, martin-mat commented on spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
> +#     result[:output] = `./cnf-testsuite all ~disk_fill ~pod_delete ~pod_network_latency ~pod_network_corruption ~pod_network_duplication ~pod_io_stress ~pod_memory_hog ~node_drain ~pod_dns_error ~ch
Either remove the commented code completely, leave it unchanged or adapt accordingly to uncommented changes. Don't adapt just partially/inconsistently.

2024-04-09 08:38 UTC, kosstennbl commented on src/tasks/utils/utils.cr
>      Log.info { "#{log_prefix} command: #{cmd}" }
This was added to have some default prefix for possibility to run ShellCmd.run with only cmd argument.
Maybe logging in ShellCmd could be rewritten to use log_prefix via Log.for(log_prefix).<...>

2024-04-09 11:01 UTC, kosstennbl commented on spec/5g/core_spec.cr
> +    result[:status].success?.should be_true end
fixed

2024-04-16 12:58 UTC, martin-mat commented
lgtm

2024-04-17 08:35 UTC, kosstennbl commented
@HashNuke @wavell  @agentpoyo Please run tests

2024-04-19 11:10 UTC, kosstennbl commented on spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
> +#     result[:output] = `./cnf-testsuite all ~disk_fill ~pod_delete ~pod_network_latency ~pod_network_corruption ~pod_network_duplication ~pod_io_stress ~pod_memory_hog ~node_drain ~pod_dns_error ~ch
Removed commented-out code

2024-04-19 11:11 UTC, kosstennbl commented on src/tasks/utils/utils.cr
>      Log.info { "#{log_prefix} command: #{cmd}" }
Used Log.for with prefix

2024-04-19 11:29 UTC, HashNuke commented
There are three tags that are failing in the build. I've run them a few times.
I've tried re-triggering a build here to confirm the failures - https://github.com/cnti-testcatalog/testsuite/actions/runs/8750289901

![CleanShot 2024-04-19 at 16 57 47@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/41e447cd-8b9a-43b7-86f1-6aeba0fe4d6b)

2024-04-19 12:20 UTC, kosstennbl commented
@HashNuke
Thanks for testing, observability and platform:observability are fixed.
Memory hog failure is probably happening due to #1973

2024-04-21 05:37 UTC, HashNuke requested changes
Posted about an error with screenshot.

2024-04-21 05:37 UTC, HashNuke commented on spec/platform/observability_spec.cr
> +      result[:status].success?.should be_true
Please look into this line. Below is the error from a build.

![CleanShot 2024-04-21 at 11 05 57@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/58b30006-ca83-4fcf-87ec-784581b4105b)

2024-04-21 05:38 UTC, HashNuke commented
@kosstennbl `platform:observability` spec still throws an error. Please check screenshot in review.
+ this PR has conflicts now.

2024-04-22 14:54 UTC, kosstennbl commented
@HashNuke Fixed conflicts, fixed platform:observability (it fails in my environment, but after fix - it looks like an environment issue rather than code issue)

2024-04-22 22:57 UTC, HashNuke commented
`platform:observability` is still failing in the latest build - https://github.com/cnti-testcatalog/testsuite/actions/runs/8791269449

Screenshot of the failure below.

![CleanShot 2024-04-23 at 04 26 28@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/5faebede-0feb-4924-92b5-ee0083fde84b)

2024-04-22 23:12 UTC, kosstennbl commented on spec/platform/observability_spec.cr
>  end
After some inspection of the changes for the failing test in this PR - it doesn't seem to me that this failure could be brought by them. Changes follow the same redesign rules as all other tests (which seem to be passing). Does this test succeed on other PRs?

2024-04-23 08:31 UTC, kosstennbl commented on spec/platform/observability_spec.cr
>  end
After further inspection - it seems that it was ensure block, which was causing issues. I'm not sure how and why it started failing after changing only logging for this block, but after last push it should be fine. Please rerun.

2024-04-23 08:31 UTC, kosstennbl commented on spec/platform/observability_spec.cr
>  end
After further inspection - it seems that it was ensure block, which was causing issues. I'm not sure how and why it started failing after changing only logging for this block, but after last push it should be fine. Please rerun.

2024-04-29 14:48 UTC, kosstennbl commented
Rebased after the output refactor merge, hopefully i haven't forgot to adapt anything.

2024-05-07 14:57 UTC, HashNuke commented
Build passing - https://github.com/cnti-testcatalog/testsuite/actions/runs/8980950321.
Will merge.

2024-05-07 14:57 UTC, merged