Prevent microservice tests from passing on errors
cnti-testcatalog/testsuite pull request #1972
Opened 2024-04-15 11:54 UTC by martin-mat

Refs: #1959

## Description
(name of issue/change)

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-04-15 15:14 UTC, taylor approved these changes
lgtm

2024-04-15 15:14 UTC, taylor reviewed
lgtm

2024-04-15 15:18 UTC, taylor commented
Updated description: 
> This updates the behaviour so the test will not pass when there is an environment or external error causing the test to not be able to do a complete validation as intended. (eg. the containers could not be inspected because of an external unrelated issue).
>
> The error is reported and the test will not pass.

2024-04-15 15:37 UTC, taylor requested changes
@martin-mat I think this should be SKIPPED vs NA for the state.

_Skipped: lack of capability, error in test, error in cnf_


cc: @denverwilliams @wavell @HashNuke

2024-04-15 15:37 UTC, taylor commented on src/tasks/workload/microservice.cr
> +      CNFManager::TestcaseResult.new(CNFManager::ResultStatus::NA, "An error occurred during container inspection")
I think this should be using the SKIPPED state and the related error type response. It also can happen earlier. See other code which uses skipped for errors such as reasonable image size

_Skipped: lack of capability, error in test, error in cnf_

```
    unless Dockerd.install(docker_insecure_registries)
      next CNFManager::TestcaseResult.new(CNFManager::ResultStatus::Skipped, "Skipping reasonable_image_size: Dockerd tool failed to install")
    end
```

https://github.com/cnti-testcatalog/testsuite/blob/4335565772c34522f809070f7210ac7c5b77c1bf/src/tasks/workload/microservice.cr#L196

or 

```
      unless check_poc(args)
        next CNFManager::TestcaseResult.new(CNFManager::ResultStatus::Skipped, "Kube State Metrics not in poc mode")
      end
```

https://github.com/cnti-testcatalog/testsuite/blob/4335565772c34522f809070f7210ac7c5b77c1bf/src/tasks/platform/observability.cr#L21

2024-04-15 19:51 UTC, martin-mat commented on src/tasks/workload/microservice.cr
> +      CNFManager::TestcaseResult.new(CNFManager::ResultStatus::NA, "An error occurred during container inspection")
> I think this should be using the SKIPPED state and the related error type response. It also can happen earlier. See other code which uses skipped for errors such as reasonable image size
> 
> _Skipped: lack of capability, error in test, error in cnf_
> 
done

2024-04-15 21:54 UTC, taylor approved these changes
lgtm

2024-04-15 21:56 UTC, wavell approved these changes

2024-04-20 19:29 UTC, agentpoyo approved these changes
LGTM

2024-04-20 19:30 UTC, merged