improvement: check if cluster is up and running
cnti-testcatalog/testsuite pull request #1995
Opened 2024-04-19 12:19 UTC by barmull

## Description
Add condition in ensure_kubeconfig! method to check the cluster's health. 

## Issues:
Refs: #1968

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-04-19 12:23 UTC, barmull commented
For testing I set KUBECONFIG into existing file, but the file is empty. Resulting that KUBECONFIG is set, but cluster is not running. See in this screenshot:
 
![image](https://github.com/cnti-testcatalog/testsuite/assets/110407915/cd3d46d9-ae1c-42c6-aae5-e0d3e87ab634)

2024-04-21 01:02 UTC, agentpoyo requested changes
This is likely held up by https://github.com/cnti-testcatalog/testsuite/pull/1964#pullrequestreview-2013146572 as the previous message is the output when kubeconfig or connection does not exist:

```
pair@cnfdev4:~/workspace/drew/testsuite-barmull$ LOG_LEVEL=debug ./cnf-testsuite setup 
CNF TestSuite version: HEAD-2024-04-21-010045-2b70ba7b
Successfully created directories for cnf-testsuite
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: VERSION: HEAD-2024-04-21-010045-2b70ba7b
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v3?: Regex::MatchData("BuildInfo{Version:\"v3.11.1\", GitCommit:\"293b50c65d4d56187cd4e2f390f0ada46b4c4737\", GitTreeState:\"clean\", GoVersion:\"go1.18.10\"" 1:"v3.11.1" 2:"11.")
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: Globally installed helm satisfies required version. Skipping local helm install.
Global helm found. Version: v3.11.1
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v2?: 
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v3?: Regex::MatchData("BuildInfo{Version:\"v3.11.1\", GitCommit:\"293b50c65d4d56187cd4e2f390f0ada46b4c4737\", GitTreeState:\"clean\", GoVersion:\"go1.18.10\"" 1:"v3.11.1" 2:"11.")
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: helm_local_version command: /home/pair/.cnf-testsuite/tools/helm/linux-amd64/helm version
No Local helm version found
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_local_version output: 
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: helm_local_version stderr: --: 1: /home/pair/.cnf-testsuite/tools/helm/linux-amd64/helm: not found

D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v2?: 
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v3?: 
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: helm_v3?: Regex::MatchData("BuildInfo{Version:\"v3.11.1\", GitCommit:\"293b50c65d4d56187cd4e2f390f0ada46b4c4737\", GitTreeState:\"clean\", GoVersion:\"go1.18.10\"" 1:"v3.11.1" 2:"11.")
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: error: Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: helm_resp (add): 
Global kubectl found. Version: 1.26
Global kubectl client version could not be checked for compatibility with server. (Server not configured?)
No Local kubectl version found
Global git found. Version: 2.34.1
No Local git version found
All prerequisites found.
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: KubectlClient::Create.namespace command: kubectl create namespace cnf-testsuite
Could not create cnf-testsuite namespace on the Kubernetes cluster
D, [2024-04-21 01:00:45 +00:00 #657279] DEBUG -- cnf-testsuite: KubectlClient::Create.namespace output: 
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: KubectlClient::Create.namespace stderr: The connection to the server localhost:8080 was refused - did you specify the right host or port?

I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite-verbose: install_apisnoop
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: apisnoop already installed. Skipping git clone for apisnoop.
Setup complete
I, [2024-04-21 01:00:45 +00:00 #657279]  INFO -- cnf-testsuite: install_kind
```

2024-04-21 01:04 UTC, agentpoyo commented
![Screenshot_2024-04-20_20-03-42](https://github.com/cnti-testcatalog/testsuite/assets/14348948/58372931-afd1-497b-a57c-a30dd4b50d44)

2024-04-23 06:35 UTC, barmull commented
In this case is not working as expected. Because the change is only in method ensure_kubeconfig!
In this PR https://github.com/cnti-testcatalog/testsuite/pull/1964 the method ensure_kubeconfig! is added into task create_namespace.
So, if you want to properly tested, you need to have this two PRs together. And then you get the same output as mine above.

2024-04-23 16:20 UTC, agentpoyo commented
> In this case is not working as expected. Because the change is only in method ensure_kubeconfig! In this PR #1964 the method ensure_kubeconfig! is added into task create_namespace. So, if you want to properly tested, you need to have this two PRs together. And then you get the same output as mine above.

I checked out your fork and both changes were included when tested.

2024-04-24 14:53 UTC, barmull commented
> ![Screenshot_2024-04-20_20-03-42](https://private-user-images.githubusercontent.com/14348948/324217064-58372931-afd1-497b-a57c-a30dd4b50d44.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTkyMDQsIm5iZiI6MTcxMzk1ODkwNCwicGF0aCI6Ii8xNDM0ODk0OC8zMjQyMTcwNjQtNTgzNzI5MzEtYWZkMS00OTdiLWE1N2MtYTMwZGQ0YjUwZDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2M2QzZWEwNjM0YTZlYWJhMDBkZGVhNmQ2NGQ3MDJlMjI5ZWUzMzI2ZWNiOTQzYTI1OTM1NjI3YTA3MjdiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4WJXvuXWlqm_GZ5J3_KZOkPGr2uJmgUMEky9F0H8J4A)

In your output is missing message 'KUBECONFIG is already set.' It seems that method ensure_kubeconfig is not executing. The method should be inserted in "create_namespace" task. So even if you set KUBECONFIG to existing config file, it should catch unhealthy cluster and raise an error. So instead of 'Could not create cnf-testsuite namespace on the Kubernetes cluster' you should see 'Exit code: 256. Executing this command 'kubectl get nodes --kubeconfig=/path/to/config/file' raised an error. For further information run command in CLI.'
![image](https://github.com/cnti-testcatalog/testsuite/assets/110407915/8d5d91d9-a3b7-488f-b759-df1427729c31)

2024-06-20 07:34 UTC, martin-mat requested changes

2024-06-20 10:51 UTC, martin-mat requested changes

2024-06-20 10:51 UTC, martin-mat commented on src/tasks/utils/utils.cr
> +    stdout_failure "Exit code: #{exit_code}. Executing this command '#{cmd}' raised an error. For further information run command in CLI."
Cluster liveness check failed: '#{cmd}' returned exit code #{exit_code}. Check the cluster and/or KUBECONFIG environment variable.

2024-06-24 12:43 UTC, martin-mat approved these changes
lgtm

2024-06-24 12:55 UTC, horecoli approved these changes
lgtm

2024-06-24 13:09 UTC, kosstennbl approved these changes
lgtm

2024-06-25 15:03 UTC, rich-l approved these changes
lgtm

2024-06-25 16:27 UTC, merged