Timer in results now human readable
cnti-testcatalog/testsuite pull request #2007
Opened 2024-04-25 21:58 UTC by wavell

## Description
(name of issue/change)

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-04-25 22:02 UTC, agentpoyo approved these changes
LGTM

2024-04-26 10:23 UTC, martin-mat requested changes

2024-04-26 10:23 UTC, martin-mat commented on src/tasks/utils/points.cr
> +      task_runtime_human = "#{task_runtime.hours} hours, #{task_runtime.minutes} minutes, and #{task_runtime.seconds} seconds"
I'd suggest to make is simpler. We are putting it to a yaml for possible engine postprocessing. %H:%M:%S is a standardized format that everyone understands and easily parsable. And task_runtime (Time::Span) as it is now will already provide this format when interpreted as a string. So From this place down, task_ruintime can be kept.

2024-04-26 10:23 UTC, martin-mat commented on src/tasks/utils/points.cr
> +      Log.info { "upsert_task: task: #{task} has status: #{status} and is awarded: #{points} points. Runtime: #{task_runtime_human} seconds" }
remove "seconds" at the end of the string.

2024-05-14 13:26 UTC, martin-mat commented
Remove this PR, a duplicate PR was merged before, such mess was created by opening a duplicate PR (and ignoring review comments in this one)

2024-05-14 16:08 UTC, closed without merging