timeouts: Redesign and unify timeouts
cnti-testcatalog/testsuite pull request #2023
Opened 2024-05-13 14:40 UTC by kosstennbl

## Description
Add common function to run a code block with a timeout. Add several global timeouts for different tasks, which can be configured via environment variables.
Several small fixes and refactoring.

## Issues:
Refs: #335

## How has this been tested:
build, test functionality on increase_decrease_capacity test.

## Types of changes:
Bug-fix, redesign

## Checklist:
**Documentation**
No updates required, ENV variables names could be added somewhere, but the documentation doesn't keep these.

**Issue**
- [ ] Tasks in issue are checked off

2024-05-14 13:13 UTC, martin-mat requested changes

2024-05-14 13:13 UTC, martin-mat commented on src/tasks/kind_setup.cr
> +    cluster.wait_until_pods_ready
I'd suggest to keep
cluster.wait_until_pods_ready()
to be clear that it is a method call

2024-05-14 13:13 UTC, martin-mat commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("reboot", "--field-selector spec.nodeName=#{worker_node}").split(",")[2]
dtto as above, string vs boolean

2024-05-14 13:13 UTC, martin-mat commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("node-failure").split(",")[2]
string/boolean

2024-05-14 13:13 UTC, martin-mat commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("node-failure", "").split(",")[2]
string/boolean

2024-05-14 13:13 UTC, martin-mat commented on src/tasks/workload/compatibility.cr
> +  cluster.wait_until_pods_ready
keep ()

2024-05-14 13:23 UTC, martin-mat commented
Additionally, it would be good to document new environment vars to USAGE.md

2024-05-15 20:49 UTC, daniel-wilmes commented
@martin-mat I have verified that the fix for node drain works as a single test and in the cert command. However, I will say the cert command does not ever finish, which appears to be a seperate issue from node drain. It may pertain to either sig_term_handled, zombie_handled, or specialized_init_system. The logging doesn't appear to indicate where we are stuck. But for this ticket I think the fix for node_drain should go in.

`---
name: cnf testsuite
testsuite_version: node-drain-fix-2024-05-15-142132-3258c691
status: 
command: ~/.mtx/konstruxx/working/tests/testCHF/cnf-testsuite cert essential
points: 100
exit_code: 0
items:
- name: increase_decrease_capacity
  status: passed
  type: essential
  points: 100
- name: volume_hostpath_not_found
  status: passed
  type: essential
  points: 100
- name: node_drain
  status: passed
  type: essential
  points: 100
- name: privileged_containers
  status: passed
  type: essential
  points: 100
- name: non_root_containers
  status: failed
  type: essential
  points: 0
- name: cpu_limits
  status: passed
  type: essential
  points: 100
- name: memory_limits
  status: passed
  type: essential
  points: 100
- name: hostpath_mounts
  status: passed
  type: essential
  points: 100
- name: container_sock_mounts
  status: passed
  type: essential
  points: 100
- name: selinux_options
  status: na
  type: essential
  points: 0
- name: hostport_not_used
  status: passed
  type: essential
  points: 100
- name: hardcoded_ip_addresses_in_k8s_runtime_configuration
  status: passed
  type: essential
  points: 100
- name: latest_tag
  status: passed
  type: essential
  points: 100
- name: log_output
  status: passed
  type: essential
  points: 100
- name: specialized_init_system
  status: failed
  type: essential
  points: 0
`

2024-05-16 08:40 UTC, kosstennbl commented on src/tasks/workload/compatibility.cr
> +  cluster.wait_until_pods_ready
Done

2024-05-16 08:40 UTC, kosstennbl commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("node-failure", "").split(",")[2]
Done

2024-05-16 08:40 UTC, kosstennbl commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("node-failure").split(",")[2]
Done

2024-05-16 08:40 UTC, kosstennbl commented on src/tasks/platform/resilience.cr
>            pod_ready = KubectlClient::Get.pod_status("reboot", "--field-selector spec.nodeName=#{worker_node}").split(",")[2]
Done

2024-05-16 08:40 UTC, kosstennbl commented on spec/platform/observability_spec.cr
>          pod_ready = KubectlClient::Get.pod_status("node-exporter-prometheus").split(",")[2]
Done, it wasn't that clear as, seemingly, values are not only "true" and "false". But as we're only interested of eqvivalence of the value to "true" or "True" (for node_ready) - changing this to boolean should be fine

2024-05-16 08:40 UTC, kosstennbl commented on src/tasks/utils/timeouts.cr
> +    sleep 2
Done

2024-05-16 08:40 UTC, kosstennbl commented
> Additionally, it would be good to document new environment vars to USAGE.md

Done

2024-05-17 21:12 UTC, martin-mat approved these changes
lgtm. Cool change, this helps to make the code more structured.

2024-06-10 19:16 UTC, martin-mat requested changes
It looks that spec tests are impacted by this change. Please analyze.
https://github.com/cnti-testcatalog/testsuite/actions/runs/9413816510

2024-06-17 11:26 UTC, kosstennbl commented
Rebased, pushed fix for increase_decrease_capacity issue, shared_database2 seems to be an issue that is not caused by timeout redesign.

2024-06-19 20:40 UTC, martin-mat commented
verified by
https://github.com/cnti-testcatalog/testsuite/actions/runs/9580002143

2024-06-19 20:42 UTC, martin-mat approved these changes
lgtm

2024-06-19 20:43 UTC, merged