cert: Add test exclusion in cert tasks
cnti-testcatalog/testsuite pull request #2051
Opened 2024-05-22 20:15 UTC by kosstennbl

## Description
Adds exclude="... ..." parameter for cert tasks in place of the previous ~... exclusion pattern.
Minor refactor of cert tasks.

Check issue for more info.

## Issues:
Refs: #2048

## Additional:
Build and functionality tested, documentation added.

2024-05-24 08:54 UTC, martin-mat requested changes
Please check just one comment, other than that OK.

2024-05-24 08:54 UTC, martin-mat commented on src/tasks/cert/cert.cr
> +    if exclude.is_a? String
can also a check for correct tasks/tests be checked? (i.e. exclusion set contains cert tests - based on points.yml - and nothing else).
Also, not sure whether this file is a good place for such 2 functions, requiring this task-oriented file to be included from elsewhere. Consider relocating it elsewhere.

2024-05-24 14:06 UTC, kosstennbl commented on src/tasks/cert/cert.cr
> +    if exclude.is_a? String
Agree, done.

2024-05-24 14:44 UTC, martin-mat requested changes

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_compatibility.cr
> +  if !exclude.empty?
do not copy/paste.
Perhaps the best would be to add a param and include that into stdout_score.

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_configuration.cr
> +  if !exclude.empty?
copy/paste

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_microservice.cr
> +  if !exclude.empty?
copy/paste

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_observability.cr
> +  if !exclude.empty?
copy/paste

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_resilience.cr
> +  if !exclude.empty?
copy/paste

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_security.cr
> +  if !exclude.empty?
copy/paste

2024-05-24 14:44 UTC, martin-mat commented on src/tasks/cert/cert_state.cr
> +  if !exclude.empty?
copy/paste

2024-05-27 08:21 UTC, kosstennbl commented on src/tasks/cert/cert_compatibility.cr
> +  if !exclude.empty?
Fixed, added new function that will call stdout_score and then add the warning if needed.

2024-06-07 06:11 UTC, martin-mat commented
github actions passed

https://github.com/cnti-testcatalog/testsuite/actions/runs/9409085660

2024-06-07 12:04 UTC, horecoli commented
LGTM 👍

2024-06-09 07:47 UTC, merged