Fix: export_published_chart correctly detects and exports tar file
cnti-testcatalog/testsuite pull request #2052
Opened 2024-05-23 08:56 UTC by svteb

## Description
Removed file globbing as it caused errors and added a new function that will detect a specific tgz file to be untared. Removed the line: `FileUtils.rm_rf(tgz_name)` as it did not work previously and now that globbing has been fixed it would cause undesired behavior (honestly I was not able to figure out why it is there at all).

## Issues:
Refs: #1947 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-05-24 14:39 UTC, martin-mat requested changes

2024-05-24 14:39 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    raise "No tar files found" if tar_files.empty?
more details about what filename was not found would make future troubleshooting easier.

2024-05-24 14:39 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    tar_files.last
A warning in case that multiple files found?

2024-05-24 14:39 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> -      FileUtils.rm_rf(tgz_name)
I guess the intention here was to remove an existing helm chart package to make sure it is pulled successfully?

2024-05-28 09:07 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +    raise "No tar files found" if tar_files.empty?
Resolved by adding a cleaner exception:

```
class TarFileNotFoundError < Exception
  def initialize(chart_name)
    super("No .tgz files found for chart #{chart_name}")
  end
end
```

2024-05-28 09:10 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +    tar_files.last
View the new change/read my new comment, this state is no longer possible.

2024-05-28 09:13 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> -      FileUtils.rm_rf(tgz_name)
Yes, the intention was to remove all prior .tgz archives (did not work because this function is incompatible with file globbing). I backtracked on this removal and remade it so it would work.

2024-05-28 09:28 UTC, svteb commented
Comments from @martin-mat were correct in pointing out some unhandled cases/lack of information provided. I've come to understand the intentions behind `FileUtils.rm_rf(tgz_name)` and decided to bring it back:

```
unless input_file && !input_file.empty?
      files_to_delete = Dir.glob("#{Helm.chart_name(helm_chart)}-*.tgz") ~> addition
      files_to_delete.each do |file|
        FileUtils.rm(file)
        puts "Deleted: #{file}"
      end ~> end of addition

      helm_info = Helm.pull(helm_chart) 
      unless helm_info[:status].success?
        puts "Helm pull error".colorize(:red)
        raise "Helm pull error"
      end
end
```

It was necessary to do it like this because `FileUtils.rm_rf` does not work with file globbing which was originally present. This addition also removed the necessity of checking for state where multiple versions of some helm archive were present (as they get deleted and the newest one gets pulled subsequentially).

Another mistake from the previous commit, that was undiscovered, was the necessity of moving this entire block before the block where tgz archive is being discovered, as the `Helm.pull(helm_chart)` command is what downloads the tgz archive. This also makes the sequence of steps somewhat more logical:

`helm_pull -> discover_tgz -> extract_tgz` whereas the previous sequence was `discover_tgz -> helm_pull -> extract_tgz`.


Furthermore I added an exception that prints better information in case no tgz file is discovered.

2024-06-03 14:48 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    tar_files.last
I checked the updated code but the point with possible multiple files is still here. At least issue a warning.

2024-06-03 14:52 UTC, martin-mat requested changes

2024-06-03 14:52 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +      raise TarFileNotFoundError.new(Helm.chart_name(helm_chart))
Better report as much information as we have now, like:
No files with glob "#{Helm.chart_name(helm_chart)}-*.tgz" found

2024-06-03 14:52 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    tgz_files = Dir.glob("#{Helm.chart_name(helm_chart)}-*.tgz")
That glob pattern is used already twice so it's worth to have it on one place (a new helper method/getter?)

2024-06-20 07:42 UTC, martin-mat requested changes

2024-06-20 07:42 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +      Log.info { "Multiple .tgz files found: #{tgz_files.join(", ")}" }
Log.warning
 plus note which one is being taken
?

2024-06-20 07:42 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    tgz_files = Dir.glob("#{Helm.chart_name(helm_chart)}-*.tgz")
comment still valid

2024-06-20 18:16 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +      Log.info { "Multiple .tgz files found: #{tgz_files.join(", ")}" }
Later on in the code the picked tgz file is logged.

2024-06-25 20:20 UTC, martin-mat requested changes

2024-06-25 20:20 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
>      elsif output_file && !output_file.empty?
simplify:
```
else 
      config = CNFManager::Config.parse_config_yml(CNFManager.ensure_cnf_testsuite_yml_path(config_file), generate_tar_mode: output_file && !output_file.empty?) 
      tgz_name = get_tgz_name(helm_chart)
end
```

2024-06-25 20:20 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    tgz_files = tgz_files(helm_chart)
avoid same identifiers for different things

2024-06-25 20:20 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +  def self.tgz_files(helm_chart)
be more explicit with method naming, for example
```
def self.find_tgz_files(helm_chart)
```

2024-06-25 20:20 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +  def self.get_tgz_name(helm_chart)
be more descriptive/explicit with method naming, for example
```
def self.get_and_verify_tgz_name(helm_chart)
```

2024-06-25 20:20 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +  def self.helm_tgz_expression(helm_chart)
better
```
def self.get_helm_tgz_expression(helm_chart)
```

2024-07-02 07:21 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
>      elsif output_file && !output_file.empty?
Good observation.

2024-07-02 07:21 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +    tgz_files = tgz_files(helm_chart)
Resolved

2024-07-02 07:21 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +  def self.tgz_files(helm_chart)
Renamed

2024-07-02 07:21 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +  def self.get_tgz_name(helm_chart)
Renamed

2024-07-02 07:21 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +  def self.helm_tgz_expression(helm_chart)
Renamed

2024-07-02 13:38 UTC, martin-mat approved these changes
lgtm, good refactoring!

2024-07-02 14:48 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +    end
I think that these "if" statements should be joined and each logical branch marked with comments:
```
if input_file && !input_file.empty?   # Input file present, Tar installation mode
    ...
else   # Input file absent, Pulled chart installation mode
    ...
end
```

2024-07-02 20:12 UTC, kosstennbl reviewed
Other than mentioned problem - looks nice: fixes the Tar problem and refactors the code

2024-07-03 08:35 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +    end
Great catch, I reduced it to one if else block, should be alright now.

2024-07-08 18:51 UTC, taylor approved these changes

2024-07-09 05:43 UTC, merged