Add exclusion of init system from single process check
cnti-testcatalog/testsuite pull request #2054
Opened 2024-05-24 07:56 UTC by horecoli

## Description
This change defines a list of specialized init systems as a constant and excludes it from the verification of a single process check.
**This PR depends on https://github.com/cnf-testsuite/k8s_kernel_introspection/pull/3 which has to be merge first.**

## Issues:
Refs: #2038

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-05-24 08:02 UTC, horecoli commented
The PR mentioned in the description, along with this PR, works fine with the dump-init and tini specialized init systems. However, there is different behavior in the case of the v6 init system (s6-svscan), which is not a single process init system but produces quite a lot of processes. So the main question is whether this case conflicts with the best practice of having single processes inside a container. I believe this needs to be discussed. Here is a screenshot showing how this test is failing with a list of processes:

![image](https://github.com/cnti-testcatalog/testsuite/assets/156072216/327fdd10-ea8e-4870-84d0-eddb297d7270)

2024-05-24 08:59 UTC, martin-mat commented
This needs discussion
@taylor @wavell @Smitholi67 

My opinion: It is OK to handle init process as an exception for single-process-type test/best practice. However, S6 init system itself does not follow single-process principle, so it is fine to have failing single-process check when S6 is used. And also for that, we should reconsider recommending S6 as a best-practice init system for containers.

2024-05-24 14:23 UTC, kosstennbl commented on src/tasks/utils/init_systems.cr
> -
Comments with links to init systems could be moved to init-systems array definition to keep information there.

2024-05-24 14:49 UTC, wavell approved these changes

2024-05-27 07:24 UTC, horecoli commented on src/tasks/utils/init_systems.cr
> -
I am not sure if it is useful to keep this in the code. A better place for it would probably be somewhere in the documentation.

2024-05-28 15:10 UTC, taylor approved these changes

2024-06-05 11:06 UTC, horecoli commented
The PR - https://github.com/cnf-testsuite/k8s_kernel_introspection/pull/3 to k8s_kernel_introspection was merged and new tag was created.  So this PR is ready to merge.

2024-06-06 19:59 UTC, martin-mat requested changes
shard.lock needs to be updated.

2024-06-07 22:22 UTC, martin-mat approved these changes
lgtm

tests passed:
https://github.com/cnti-testcatalog/testsuite/actions/runs/9422178235

2024-06-07 22:22 UTC, merged