Change: Cluster setup exception message shortened
cnti-testcatalog/testsuite pull request #2055
Opened 2024-05-24 07:56 UTC by svteb

## Description
As explained in the referenced issue, there was an unnecessary stack trace printed out in `install_cluster_tools` and `uninstall_cluster_tools` if `./cnf-testsuite setup` has not been run. This was remediated by replacing the `raise` command with `puts`. Additionally I made the informative message more explicit for new users.

## Issues:
Refs: #1926 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-05-24 14:18 UTC, martin-mat requested changes

2024-05-24 14:18 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    puts "Please run: ./cnf-testsuite setup"
puts "Please run: cnf-testsuite setup"

2024-05-24 14:18 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    puts "Please run: ./cnf-testsuite setup"
dtto

2024-05-27 14:20 UTC, martin-mat approved these changes
~lgtm~

2024-06-07 07:25 UTC, martin-mat requested changes

2024-06-07 07:25 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    puts "Please run: cnf-testsuite setup"
This message is insufficient. Bear in mind a difference between logging and console output. Just console output alone should give sufficient information about the error that happened. End user needs to get the information what happened (namespace does not exist) and suggested remediation. Additionally, red colorwould be appropriate (use stdout_failure)

2024-06-07 07:25 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    puts "Please run: cnf-testsuite setup"
dtto

2024-06-11 20:00 UTC, svteb commented on src/tasks/cluster_setup.cr
> +    puts "Please run: cnf-testsuite setup"
![image](https://github.com/cnti-testcatalog/testsuite/assets/133103846/1b8967fe-c393-4c7d-b136-733e0132adf1)
What about this output? I think it is quite descriptive, the line break might have been unnecessary.

Pushed with the new change.

2024-06-19 20:49 UTC, martin-mat requested changes

2024-06-19 20:49 UTC, martin-mat commented on spec/cluster_setup_spec.cr
> +    (/Error: Namespace cnf-testsuite does not exist.\nPlease run 'cnf-testsuite setup' to create the necessary namespace./\
Usually we don't depend on exact wording of error messages. Can we have just a key part here?

2024-06-19 20:49 UTC, martin-mat commented on spec/cluster_setup_spec.cr
> +    (/Error: Namespace cnf-testsuite does not exist.\nPlease run 'cnf-testsuite setup' to create the necessary namespace./\
dtto

2024-06-19 20:49 UTC, martin-mat commented on spec/cluster_setup_spec.cr
> +    (/Error: Namespace cnf-testsuite does not exist.\nPlease run 'cnf-testsuite setup' to create the necessary namespace./\
dtto

2024-06-19 20:49 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    Log.info { "#{e.message}" }
shouldn't this be Log.error { ... } ?
Is just such propagated error message sufficient to know what happened from the logs?
Bear in mind that the console output and log output can be different channels/files.

2024-06-19 20:49 UTC, martin-mat commented on src/tasks/cluster_setup.cr
> +    Log.info { "#{e.message}" }
dtto

2024-06-20 09:00 UTC, svteb commented on src/tasks/cluster_setup.cr
> +    Log.info { "#{e.message}" }
Moved it to Log.error, the log message should be sufficient.
![image](https://github.com/cnti-testcatalog/testsuite/assets/133103846/88188a54-6b1e-466f-9700-a77e8a503708)

2024-06-25 19:58 UTC, martin-mat approved these changes
lgtm

2024-06-26 08:27 UTC, martin-mat approved these changes

2024-06-28 08:27 UTC, kosstennbl approved these changes
LGTM, should make spec test output clearer and less confusing. 
Pls add comment to PR about reason for removing `Log.info { "install_cluster_tools" }`

2024-06-28 08:31 UTC, svteb commented
> LGTM, should make spec test output clearer and less confusing. Pls add comment to PR about reason for removing `Log.info { "install_cluster_tools" }`

The clustertools.install method prints that cluistertools installation is ongoing:

```
  def self.install(host_namespace = true)
    Log.info { "ClusterTools install" }
    if host_namespace
      File.write("cluster_tools.yml", ManifestHostNamespaceTemplate.new().to_s)
    else
      File.write("cluster_tools.yml", ManifestTemplate.new().to_s)
    end
    KubectlClient::Apply.file("cluster_tools.yml", namespace: self.namespace!)
    wait_for_cluster_tools
  end
```

So just replication removal.

2024-07-02 15:31 UTC, collivier approved these changes

2024-07-02 16:16 UTC, rich-l approved these changes
lgtm

2024-07-02 18:55 UTC, merged