[MAINTENANCE] Create new namespace - cnf-default
cnti-testcatalog/testsuite pull request #2056
Opened 2024-05-31 08:37 UTC by barmull

- remove helm_install_namespace from all samples
- cnfs are deployed into cnf-default namespace
- add condition into cleanup to terminate pods from cnf-default namespace

## Description
The best practice is not installing CNF to the `default` namespace on cluster.

## Issues:
Refs: #2039

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [X] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-06-10 13:50 UTC, martin-mat approved these changes
~~lgtm~~

2024-06-10 14:22 UTC, horecoli commented
LGTM

2024-06-10 14:26 UTC, horecoli approved these changes

2024-06-10 19:11 UTC, martin-mat requested changes
Multiple spec tests failing. This needs analysis and possibly adaptations of code.
https://github.com/cnti-testcatalog/testsuite/actions/runs/9450159597

2024-06-26 15:28 UTC, martin-mat requested changes

2024-06-26 15:28 UTC, martin-mat commented on CNF_TESTSUITE_YML_USAGE.md
> +<<<<<<< HEAD
wrong conflict resolution

2024-06-26 15:28 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +  def self.get_default_namespace(config)
simpler:
```
  def self.get_default_namespace(config)
    install_method = CNFManager.cnf_installation_method(config)
    case install_method[0]
    when Helm::InstallMethod::HelmChart, Helm::InstallMethod::HelmDirectory
      if !config.cnf_config[:helm_install_namespace].empty?
        config.cnf_config[:helm_install_namespace]
      else
        DEFAULT_CNF_NAMESPACE
      end
    else
      "default"
    end
  end
```

2024-06-26 15:28 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
>      when Helm::InstallMethod::HelmChart, Helm::InstallMethod::HelmDirectory
I think get_default_namespace should be still used here. Even if a similar condition needs to be kept for setting helm_namespace_option.

2024-06-26 15:28 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    if helm_install_namespace.empty?
What if the install method is a manifest?

2024-07-02 08:26 UTC, kosstennbl commented on src/tasks/workload/microservice.cr
> +    resources = Helm.workload_resource_kind_names(resource_ymls)
It seems, that there, if resource.metadata.namespace wouldn't be found - it would set up to "default", as mentioned in the Helm library: https://github.com/cnf-testsuite/helm/blob/46b0c7f75a4bb6aac8318dc2c37daa875903ee2f/helm.cr#L242

It wouldn't affect test in any way as resources[n][:namespace] isn't used there, but maybe for clarification and to avoid possible misunderstandings - it would be better to add "get_default_namespace()" there somewhere

2024-07-17 15:02 UTC, martin-mat requested changes

2024-07-19 08:18 UTC, martin-mat commented
needs rebase and conflict resolution

2024-07-29 08:33 UTC, martin-mat requested changes

2024-07-29 08:33 UTC, martin-mat commented on spec/workload/state_spec.cr
> +      result[:status].success?.should be_true
How is this change related to changing default namespace?

2024-07-29 15:41 UTC, barmull commented on spec/workload/state_spec.cr
> +  it "'elastic_volumes' should pass if the cnf does not use volumes that are elastic volume", tags: ["elastic_volume"]  do
During testing of 'elastic_volumes', I noticed that both spec tests had the same heading. I assumed that one spec test should fail and the other should pass, so I believe this is a typo, and I fixed it. However, this change is not within the scope of this PR, so I can remove it if necessary or if I am mistaken.
![image](https://github.com/user-attachments/assets/075506cc-b272-46e7-98f4-d1d028b87b95)

2024-07-29 16:05 UTC, barmull commented on spec/workload/state_spec.cr
> +      result[:status].success?.should be_true
The command 'KubectlClient::Get.resource_wait_for_install("Pod", "mysql-0")' was ineffective because it didn't specify a namespace. Without a defined namespace, it defaults to the default namespace, which may not be correct in some cases. I believe it is not good practice to wait for installation outside of cnf_setup or a test.

The command attempted 180 times to locate the pod, but the pod was installed into cnf-default.
![image](https://github.com/user-attachments/assets/86935c75-67b3-42c8-83f2-dd25593e70de)

Removing line 46 is related to this change because the command requires the namespace option, which is difficult to specify outside of the cnf_setup method.

2024-07-29 17:44 UTC, martin-mat commented on spec/workload/state_spec.cr
> +  it "'elastic_volumes' should pass if the cnf does not use volumes that are elastic volume", tags: ["elastic_volume"]  do
those tests and their description need a closer look. I don't think that proposed change is correct. Anyway please exclude this change from this pr and create a new issue for it.

2024-07-29 18:21 UTC, martin-mat requested changes

2024-07-29 18:21 UTC, martin-mat commented on spec/workload/microservice_spec.cr
> -      KubectlClient::Delete.command("pvc data-test-mariadb-0 -n wordpress")
I think this pvc delete is needed.
Perhaps it would be simplest to keep 'wordpress' namespace in ndn-multi-db-connections-fail/cnf-testsuite.yml as it was originally.

2024-07-29 18:26 UTC, martin-mat commented on spec/workload/state_spec.cr
> +      result[:status].success?.should be_true
Ok, thanks for explanation. Let's keep it then.

2024-07-29 18:36 UTC, martin-mat requested changes

2024-07-29 18:36 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +    default_namespace = CNFManager.get_default_namespace(config)
this can be removed if I'm not mistaken.

2024-07-30 07:43 UTC, barmull commented on spec/workload/microservice_spec.cr
> -      KubectlClient::Delete.command("pvc data-test-mariadb-0 -n wordpress")
ok, I'll take back this change.

2024-07-30 17:52 UTC, martin-mat approved these changes
lgtm

2024-07-31 17:35 UTC, rich-l approved these changes
lgtm

2024-07-31 19:30 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +      helm_install_namespace = config.cnf_config[:helm_install_namespace]
Seems like unused variable

2024-07-31 19:31 UTC, Smitholi67 approved these changes
lgtm

2024-07-31 19:32 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
>        helm_install_namespace = parsed_config.cnf_config[:helm_install_namespace]
ditto

2024-07-31 19:33 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
>      helm_install_namespace = config.cnf_config[:helm_install_namespace]
ditto

2024-07-31 19:34 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +      helm_install_namespace = config.cnf_config[:helm_install_namespace]
Probably it would be best to search through all definitions of helm_install_namespace variable and check if all of them are necessary

2024-08-05 08:18 UTC, kosstennbl approved these changes
LGTM

2024-08-05 14:26 UTC, horecoli approved these changes
lgtm

2024-08-05 18:21 UTC, merged