docs: Add linter for the documentation
cnti-testcatalog/testsuite pull request #2089
Opened 2024-06-27 08:21 UTC by kosstennbl

## Description
Add mdl as a linter for new cnf-testsuite documentation 
Add custom rules for keeping format of the documentation 
Add lint to git workflows to run mdl.
Remove docs directory from .gitignore
Fix small issues in documentation for linter to pass.

## Issues:
Refs: #1945

2024-06-27 14:23 UTC, svteb requested changes

2024-06-27 14:26 UTC, kosstennbl commented on docs/mdl-TTDS-rules.rb
> +rule "TTDS004", "Tests should have all required sub-sections" do
Rule naming style was taken from built-in MDL rules: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
Thought, that it would be better to keep it the same.

2024-06-27 14:27 UTC, kosstennbl commented on docs/mdl-TTDS-rules.rb
> +rule "TTDS005", "TOC should not contain links to non-existent tests" do
ditto

2024-06-28 08:20 UTC, martin-mat commented
1. I'm wondering whether it is a good place to store *.rb rules in the doc directory. To me it looks like CI tooling issue and perhaps should be somewhere else, like /utils dir ...?
2. How do we handle introduced ruby dependency (although for CI/testing purposes only)?
3. Can we exclude the doc linters/workflow from triggering the crystal workflow?

2024-07-02 13:14 UTC, martin-mat approved these changes
lgtm

2024-07-02 15:29 UTC, Smitholi67 approved these changes
lgtm

2024-07-02 16:09 UTC, rich-l approved these changes
lgtm

2024-07-02 19:47 UTC, merged