hardcoded-ip-test: Redesign test, add more info on fail
cnti-testcatalog/testsuite pull request #2096
Opened 2024-07-01 13:38 UTC by kosstennbl

## Description
Add information about file location, line numbers and lines themselves if the hardcoded_ip_addresses_in_k8s_runtime_configuration fails

## Issues:
Refs: #2093

## How has this been tested:
Covered by existing integration testing

## Types of changes:
 Bug fix (non-breaking change which fixes an issue)

2024-07-02 13:29 UTC, martin-mat requested changes

2024-07-02 13:29 UTC, martin-mat commented on src/tasks/workload/configuration.cr
> +    File.open("#{destination_cnf_dir}/helm_chart.yml") do |file|
Can #{destination_cnf_dir}/helm_chart.yml be stored in a variable so it does need to be copy/pasted?

2024-07-02 13:29 UTC, martin-mat commented on src/tasks/workload/configuration.cr
> +    unless found_violations.empty?
simplify:
```
    if found_violations.empty?
      CNFManager::TestcaseResult.new(CNFManager::ResultStatus::Passed, "No hard-coded IP addresses found in the runtime K8s configuration")
    else
      stdout_failure("Hard-coded IP addresses found in #{destination_cnf_dir}/helm_chart.yml")
      found_violations.each do |violation|
        stdout_failure("  * Line #{violation[:line_number]}: #{violation[:line]}")
      end
      CNFManager::TestcaseResult.new(CNFManager::ResultStatus::Failed, "Hard-coded IP addresses found in the runtime K8s configuration")
    end

2024-07-02 14:08 UTC, kosstennbl commented on src/tasks/workload/configuration.cr
> +    File.open("#{destination_cnf_dir}/helm_chart.yml") do |file|
Yep, it repeated 4 times, good idea, done.

2024-07-02 14:09 UTC, kosstennbl commented on src/tasks/workload/configuration.cr
> +    unless found_violations.empty?
Felt about test results returns as a "separate code block", but agree that it makes sense to join outputs like this, done.

2024-07-02 15:27 UTC, collivier approved these changes

2024-07-02 15:32 UTC, Smitholi67 approved these changes

2024-07-02 16:12 UTC, rich-l approved these changes
lgtm

2024-07-03 07:14 UTC, svteb commented on src/tasks/workload/configuration.cr
> +        elsif matches = line.scan(/([0-9]{1,3}[\.]){3}[0-9]{1,3}/)
Can a case where there are multiple IPs on one line even happen?

2024-07-03 07:53 UTC, svteb approved these changes

2024-07-03 21:40 UTC, merged