Feat: Rework k8s_tshark functionality and apply the changes in tests
cnti-testcatalog/testsuite pull request #2097
Opened 2024-07-01 20:45 UTC by svteb

## Description
**Commit message:**

- Prior functionality was bound to fixed time of execution (120s), which introduced problems in testing (tshark session ending before the test began).
- New functionality mainly implements infinite tshark execution along with the possibility of terminating it when deemed appropriate. This is complemented with robust error handling and termination of the tshark process on unexpected crashes during initialization. NOTE: The main tests currently do not handle states where a crash could occur elsewhere and thus a hanging tshark session can still happen (although unlikely).
- The module is properly commented which should allow the user to get a quick understanding of its functionality.
- The user functionality remains the same with easier-to-comprehend function names.
- Handling of PIDs is rather problematic due to the nature of exec_by_node_bg function, which does not return the PID of the tshark process but rather the PID of the shell executing it (unverified). This is why the retrieval of PID may seem rather complicated (especially the pid_command variable). Possible solutions are listed in a comment, but these don't quite work for various reasons (globbing issues, return of incorrect PID, etc.). As for the kill -15 and kill -9 repetition, some tshark session would get stuck in a zombie state if the commands were not executed in this order.

**Additional info for reviewers:**

The spec tests that verify the correctness of this change are: `5g, oran, core`. For some reason I cannot deploy the `oran` CNF properly so the testing will probably have to be left for github actions. Some of the changes that were made removed the necessity of nesting in the main workload functions (which was thus removed). The class oriented design was somewhat necessary to allow for saving the state of the capture and its future termination. This should also resolve #2072 .

As for the code, a non-trivial amount of time was spent fine-tuning the behavior around PIDs and this is the only configuration I got to behave correctly, although I admit some parts don't look all that pretty. The main problems stem from kubectl_client which is eventually called to spawn the process, since the Process.new/run functions do not return the correct PID/print output I could not really achieve this any other way.

## Issues:
Refs: #2072 #2087

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-07-02 14:11 UTC, kosstennbl requested changes
As was discussed online, changes for timeout design and possible nil value of "capture" variable

2024-07-03 09:04 UTC, svteb commented on src/tasks/utils/oran_monitor.cr
> +    if capture.regex_match?(/e2ap\.successfulOutcome_element[^$]*e2ap.ric_ID/)
There is a missing check for capture being Nil.

2024-07-03 09:04 UTC, svteb commented on src/tasks/utils/k8s_tshark.cr
> +        end
For this timeout logic, the `repeat_with_timeout` function can be used.

2024-07-03 09:04 UTC, svteb commented on src/tasks/workload/5g_validator.cr
> +      capture.begin_capture_by_label(smf_key, smf_value, command)
I am unsure about this being a single capture and will need to review if something wrong could happen.

2024-07-04 08:35 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +      e2_found = ORANMonitor.e2_session_established?(capture.not_nil!)
Resolved

2024-07-04 08:35 UTC, svteb commented on src/tasks/utils/oran_monitor.cr
> +    if capture.regex_match?(/e2ap\.successfulOutcome_element[^$]*e2ap.ric_ID/)
Resolved

2024-07-04 08:35 UTC, svteb commented on src/tasks/utils/k8s_tshark.cr
> +        end
Resolved

2024-07-04 08:47 UTC, svteb commented on src/tasks/workload/5g_validator.cr
> +      capture.begin_capture_by_label(smf_key, smf_value, command)
It actually did not make sense for this to be a single capture, I made some changes to the task to make it somewhat sensible. **TL;DR:** As I have mentioned above in the pull request description, the `smf_upf_heartbeat` task did not measure/test anything properly. With the newest change I've pushed it might be a little more sensible.

**Long version:**

The `smf_upf_heartbeat` task is not even documented, which makes deciphering what it should do and how even harder. By reading the code and applying some speculation, the objective is probably to: 
`measure some baseline state` > `run some disruptive behavior` > `measure again during disruptive state` > `compare the two states to determine if the 5g remained "persistent"`. 

With the original implementation the "measuring" stages took around 1 second, during which nothing really was measured. I upped that to 60 for both so that we get some actual data to be compared. Upon running the test I saw that the measured counts were different before and after disruption (as expected). The spec tests pass as well. As this test is not in the essential category I think we can leave it as is for now.

2024-07-05 11:04 UTC, kosstennbl commented on src/tasks/workload/5g_validator.cr
> +      capture.terminate_capture
Seeing this - i've got an idea for possible improvement:
Maybe capture could work like File.open(), take block of code and close the capture automatically after in "ensure" statement. This way it would be possible to get rid of need for terminating the captures and having "finalize" method for Capture object.

2024-07-05 11:32 UTC, kosstennbl commented on src/tasks/utils/k8s_tshark.cr
> +      end
Proposal:
```
private def retrieve_pid(command : String, pid_file : String)
  begin
    # Store the pid of the tshark process.
    ClusterTools.exec_by_node_bg(command, @node_match.not_nil!)

    # Wait for pidfile to be readable using repeat_with_timeout
    pid_found = repeat_with_timeout(timeout: 10, errormsg: "Timed out while waiting for PID file.") do
      File.exists?(pid_file) && File.size(pid_file) > 0
    end
    if pid_found
      @pid = File.read(pid_file).strip.to_i
      Log.info { "tshark process started with PID: #{@pid}" }
    else
      # Attempt to kill the capture process if it was started.
      ClusterTools.exec_by_node_bg("pkill -15 tshark && sleep 1 && pkill -9 tshark", @node_match.not_nil!)
      @pid = nil
      raise K8sTsharkError.new("Could not retrieve the PID of the tshark process")
    end
  ensure
    File.delete(pid_file) if File.exists?(pid_file)
  end
end
```
Fixed usage of repeat_with_timeout, simplified error handling and error logging.

2024-07-05 11:43 UTC, kosstennbl commented on src/tasks/utils/k8s_tshark.cr
> +    private property node_match : JSON::Any?
Idea of this object being "reusable" bothers me a little, but i don't think its too big of a problem and i can't think of a solution that would fix this and would be implementable in a reasonable time.

2024-07-09 08:22 UTC, svteb commented on src/tasks/workload/5g_validator.cr
> +      capture.terminate_capture
I added this option and its now used in both suci_enabled and in smf_upf_heartbeat tasks. As we discussed in a meeting, this cannot quite be applied to the oran test in `cnfmanager.cr` because the beginning and end of capture there spans some 400 lines, maybe after refactor of `sample_setup` something can be figured out.

2024-07-09 08:23 UTC, svteb commented on src/tasks/utils/k8s_tshark.cr
> +      end
Changed.

2024-07-09 08:29 UTC, svteb commented on src/tasks/utils/k8s_tshark.cr
> +    private property node_match : JSON::Any?
I also thought about this and the simplest option would be to use some flags that would effectively make the object unusable after the first capture has begun, but  I do not think it is necessary (just more bloat with if/else checks). There are warnings and error handling for the programmer to figure out if he is doing something wrong and considering that this function is not used in that many places it probably does not matter, furthermore the block `open-with` option from the above review will somehow hide this functionality. Also singleton does not work here as we can have multiple captures running at the same time (might be desired in the future).

2024-07-09 14:02 UTC, martin-mat approved these changes
lgtm

2024-07-09 15:12 UTC, collivier approved these changes

2024-07-09 15:55 UTC, Smitholi67 approved these changes
lgtm

2024-07-09 16:30 UTC, merged