cnf_setup: Exit on setup failure or timeout
cnti-testcatalog/testsuite pull request #2114
Opened 2024-07-29 08:29 UTC by kosstennbl

## Description
Fix handling unsuccessful cnf setup, if resources are not ready after timeout - then setup should fail with exit 1. Change specs accordingly, replace wait_count=0 with new option "ignore_setup_timeout".
Add cnf_setup function to ShellCmd and use it for
installation of CNFs during specs.

## Issues:
Refs: #1937 #2083

2024-07-29 15:39 UTC, martin-mat requested changes

2024-07-29 15:39 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +          stdout_success "\e[1A\e[K" + "Waiting for resource (#{current_resource_number}/#{total_resource_count}): #{resource[:kind]} #{resource[:name]}"
I'd suggest to do 
```
stdout_success  "\e[K" + "Waiting for resource (#{current_resource_number}/#{total_resource_count}): #[{resource[:kind]}] #{resource[:name]}" + "\e[1A"
```
and not to do extra new line on 824
and print extra "\e[K" after the loop. 

Advantages of such modifications:
- this will not leave last status line on console. Leaving is somehow not consistent with idea having this just as an intermediate console info (and anyway it is reported again on 835 in case of error)
- on screens without ansi support (and when redirected to a file) no unnecessary extra line will be present after printout at 824

Maybe, even better, and to be usable also on other places, we can define common functions
stdout_update_line(str) -> stdout_success("\e[K" + str + "\e[1A")
stdout_cleanup_line() -> stdout_success("\e[K")

Also, marking the kind of the resource would help, maybe square brackets?
```
Waiting for resource (1/1): [Deployment] coredns-coredns
```

2024-07-30 13:04 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +          stdout_success "\e[1A\e[K" + "Waiting for resource (#{current_resource_number}/#{total_resource_count}): #{resource[:kind]} #{resource[:name]}"
Suggestion haven't worked as expected, "\e[1A" in the end of the string moves the cursor, but next print that doesn't clear the line works incorrectly (it writes on top of current text). Possible solution is doing cleanup_line before each next print, but i don't like that solution. I think that each print should leave the terminal in a stable state. 

Check current solution, it writes "All CNF resources are up!" by replacing last "Waiting for resource" line and has separate function for prints like these.

2024-07-30 18:03 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +          stdout_success "\e[1A\e[K" + "Waiting for resource (#{current_resource_number}/#{total_resource_count}): #{resource[:kind]} #{resource[:name]}"
looks ok, thanks.

2024-07-30 18:35 UTC, martin-mat requested changes

2024-07-30 18:35 UTC, martin-mat commented on src/tasks/utils/utils.cr
> +def stdout_success_same_line(msg)
maybe better would be to add a new param to stdout_success(msg, same_line=false)

2024-07-30 18:35 UTC, martin-mat commented on src/tasks/utils/utils.cr
> +def stdout_failure_same_line(msg)
dtto

2024-07-30 18:35 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +          # \e[1A\e[K is a sequence that allows to clear current line and place cursor at its beginning
remove this comment

2024-07-30 18:35 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +        stdout_success "Waiting for resource availability, timeout for each resource is #{wait_count} seconds \n"
just nitpicking - better if this \n is done as an escape sequence to be consistent with what it prepares for. And it will not print excess newline in case that the terminal does not support them.

2024-07-30 18:35 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +            stdout_failure "Preffered course of actions would be to investigate the resource in cluster, then call cnf_cleanup and try to reinstall the CNF."
Preffered -> Recommended

2024-07-30 18:37 UTC, martin-mat commented
It looks that this change did its job and revealed issues with cnf setup in spec tests. They need to be addressed though.

2024-07-30 19:26 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +        stdout_success "Waiting for resource availability, timeout for each resource is #{wait_count} seconds \n"
This will require creating additional function or parameter for printing with newline before carriage return and line clear. It seems excess to me.

2024-07-30 19:30 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +          # \e[1A\e[K is a sequence that allows to clear current line and place cursor at its beginning
Moved appropriately

2024-07-30 19:31 UTC, kosstennbl commented on src/tasks/utils/utils.cr
> +def stdout_failure_same_line(msg)
Done

2024-07-30 19:31 UTC, kosstennbl commented on src/tasks/utils/utils.cr
> +def stdout_success_same_line(msg)
Done

2024-07-30 19:31 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +            stdout_failure "Preffered course of actions would be to investigate the resource in cluster, then call cnf_cleanup and try to reinstall the CNF."
Done

2024-07-30 20:14 UTC, kosstennbl commented
Issues with "envoy" chart are brought by #2116, they should be resolved for CI to pass.

2024-07-31 10:22 UTC, martin-mat commented
the change looks fine for me now, I will approve after the envoy issue is addressed.

2024-08-05 18:24 UTC, martin-mat commented
rebase pls

2024-08-06 12:12 UTC, martin-mat requested changes

2024-08-06 12:12 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +            stdout_failure "Recommented course of actions would be to investigate the resource in cluster, then call cnf_cleanup and try to reinstall the CNF."
Recommended

2024-08-06 12:16 UTC, martin-mat approved these changes
lgtm

2024-08-14 06:22 UTC, svteb approved these changes
lgtm

2024-08-15 14:15 UTC, merged