Removal and exchange duplicate test for privileged containers
cnti-testcatalog/testsuite pull request #2119
Opened 2024-07-31 15:40 UTC by horecoli

## Description
This change removes the Kubescape implementation of test for privileged containers. The reason behind this decision is the absence of functionality to exclude containers from the test. Instead, it has been replaced with an in-house implementation of this test, which has been renamed from "privileged" to "privileged_containers".

## Issues:
Refs: #2115

## How has this been tested:
 - [x] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-08-01 12:54 UTC, kosstennbl requested changes
TEST_DOCUMENTATION.yml requires a small change.
utils_spec.cr:181-183, seems that prefix is also needed to be changed.

2024-08-01 12:54 UTC, kosstennbl commented on spec/workload/security_spec.cr
>        (/Found.*privileged containers.*coredns/ =~ result[:output]).should be_nil
This output check doesn't seem right when comparing to test outputs, the test will always pass.

2024-08-01 12:54 UTC, kosstennbl commented on spec/workload/security_spec.cr
> +  it "'privileged_containers' should pass with a non-privileged cnf", tags: ["privileged"]  do
Maybe tag could be changed to privileged_containers? And same would be used for privilege escalation tests.

2024-08-01 12:59 UTC, horecoli commented on spec/workload/security_spec.cr
> +  it "'privileged_containers' should pass with a non-privileged cnf", tags: ["privileged"]  do
no, I don't think so, it was same also before without changing tag. Tag is probably used for all privileged tests including escalation.

2024-08-01 13:33 UTC, horecoli commented on spec/workload/security_spec.cr
>        (/Found.*privileged containers.*coredns/ =~ result[:output]).should be_nil
I am not sure what you mean, I didn't change anything related to output, I just renamed test during its execution.

2024-08-05 08:42 UTC, kosstennbl commented on .github/workflows/actions.yml
> +        LOG_LEVEL=info ./cnf-testsuite all ~compatibility ~resilience ~reasonable_startup_time ~reasonable_image_size ~platform ~privileges ~increase_capacity ~decrease_capacity ~install_script_helm
I think task names are used there, not spec tags. Should be ~privileged_containers

2024-08-05 08:42 UTC, kosstennbl commented on .github/workflows/actions.yml
> +        LOG_LEVEL=info ./cnf-testsuite all ~resilience ~compatibility ~pod_network_latency ~platform ~privileges ~increase_capacity ~decrease_capacity ~ip_addresses ~liveness ~readiness ~rolling_upda
ditto

2024-08-05 09:05 UTC, horecoli commented on .github/workflows/actions.yml
> +        LOG_LEVEL=info ./cnf-testsuite all ~compatibility ~resilience ~reasonable_startup_time ~reasonable_image_size ~platform ~privileges ~increase_capacity ~decrease_capacity ~install_script_helm
No, there was just "privileged" before, which was tag  and not a task name, that was the reason why I changed that only in last commit when I changed tag.

2024-08-05 09:19 UTC, horecoli commented on .github/workflows/actions.yml
> +        LOG_LEVEL=info ./cnf-testsuite all ~resilience ~compatibility ~pod_network_latency ~platform ~privileges ~increase_capacity ~decrease_capacity ~ip_addresses ~liveness ~readiness ~rolling_upda
done

2024-08-05 09:20 UTC, horecoli commented on spec/workload/security_spec.cr
>        (/Found.*privileged containers.*coredns/ =~ result[:output]).should be_nil
but yes, there was issue with regex before, which we didn't know about it. I fixed it in last commit. Thanks.

2024-08-05 10:05 UTC, kosstennbl approved these changes
LGTM

2024-08-05 19:07 UTC, martin-mat approved these changes
lgtm

2024-08-06 22:52 UTC, rich-l approved these changes
lgtm

2024-08-07 06:04 UTC, merged