Feat: Transformer for old version of config
cnti-testcatalog/testsuite pull request #2133
Opened 2024-08-12 09:59 UTC by svteb

## Description
The transformer transforms the old config according to the structure proposed in #2129. Some more changes will need to be done in #2129 or later to accept a Hash as an input for the class initialization.

The current structure is still undetermined and depends on #2129, further changes will be made accordingly. There are still some erroneous areas, for example the `transform_install_method` likely does not conform to the new structure.

## Issues:
Refs:  #2130

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-08-12 10:53 UTC, martin-mat commented
Can the architecture be made more future-proof towards possible future config versions?
- Identify source version of the confing on the input
- Have possibility to tell which config version one needs to transform to (perhaps with hardcoded config version actually used by the testsuite as a constant somewhere)
- Make an easy way for future introduction of config v3.0 and newer, with possibility to transform from 1.0 and 2.0

2024-08-12 11:08 UTC, martin-mat commented
Additionally, how about error handling? Like non-supported config keys on input? Maybe other error conditions?

2024-08-12 12:38 UTC, kosstennbl requested changes
Overall comment - feels a bit too repetitive, maybe consider adding some private methods to the class that would shorten the code.

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +    end
Maybe it is possible to take the whole list from container_names key and copy it somehow?

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +        "emergency" => @old_config["emergency"]?.as_s
These parameters are under fiveG_core hash. I think they should be accessible as @old_config["fiveG_core"]["amf_service_name"]

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +    end
Install method is not needed to be transferred, v2 config uses this parameter differently (or won't use at all).
(I should have mentioned that in the issue, but it wasn't clear at the moment)

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +        "namespace" => @old_config["release_name"]?.as_s
Should be unpacked differently:
"helm_repo_name" => @old_config["helm_repository"]["name"]?.as_s
"helm_repo_url" => @old_config["helm_repository"]["repo_url"]?.as_s,
...

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +        "namespace" => @old_config["namespace"]?.as_s
old - helm_install_namespace

2024-08-12 12:38 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +        "config_version" => "2.0", # New version identifier
Making current config version a constant in CNFInstall module fells like a better solution

2024-08-13 07:52 UTC, svteb commented
> Additionally, how about error handling? Like non-supported config keys on input? Maybe other error conditions?

I believe that this is out of scope of this ticket. These could all be considered validation. 

To my knowledge the v1 config does not have a validator that we could reuse to verify the input data, but considering that all the sample/example cnfs are currently (hopefully) deployable I do not find it necessary to verify the input data. Afterall they will all be replaced in step 3 of #2120 epic.

As for the output validation, that also probably does not fall in scope of this ticket as that should be included in #2129 which is the main parser for v2. The current flow of the program for v2 config should be something like this:

1. `./cnf-testsuite cnf_setup config.yml`
2. Execute parser from #2129  ~> Checks if the config is v1 or v2.
3. If v1, execute the transformer code which will return a transformed config back to the parser from #2129.
4. Parser then validates the input, etc.

As for error handling, the current format of `"key" => @old_config["key"]?.as_s` assures that if some key is not present its value will be stored as nil (which is inconsequential as the v2 class will also have nil values). Non-supported config keys are not recognized by the transformer because it looks only for the valid keys. In case of nested keys, I first check for existence of their parent. There should not be any conditions under which an error is given.

**Input validation:**
I simply don't find this necessary, do we really want to spend time on validating the v1 config if we intend to replace it in the next couple of weeks and the testsuite worked without it for some time now?

2024-08-13 07:55 UTC, svteb commented
> Can the architecture be made more future-proof towards possible future config versions?
> 
> * Identify source version of the confing on the input
> * Have possibility to tell which config version one needs to transform to (perhaps with hardcoded config version actually used by the testsuite as a constant somewhere)
> * Make an easy way for future introduction of config v3.0 and newer, with possibility to transform from 1.0 and 2.0

This is a valid point, I will attempt to generalize the process/add more private functions.

2024-08-13 09:02 UTC, svteb commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +    end
Interim solution.

`"container_names" => @old_config["container_names"]?.as_a,`

2024-08-13 09:03 UTC, svteb commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +    end
Removed and will not be stored.

2024-08-13 09:29 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_transformer.cr
> +        "emergency" => @old_config["emergency"]?.as_s
My mistake, old config doesn't have additional structure for 5g parameters.

2024-09-04 08:04 UTC, svteb commented
**Short summary of what was attempted during implementation and the solution:**

I made multiple attempts at creating a generic solution that would allow for future extendibility, these have unfortunately hit some really hard roadblocks. The outline for a generic solution encompassed these properties:

1. Output of the transformer is easily parsed by the appropriate config class it is being converted to.
2. Future config formats (v2,3,...) would not require any changes to the main ConfigTransformer class, they would merely require a new appropriate rule set made up of transformations to be added.
3. The transformation rule sets would be easy to write (old key chain -> new key chain).
4. The transformer would resolve any reasonably expected/correct YAML configs.

**The approaches:**
**Rule sets**
The advanced approach would allow for rules like these to be defined:

```
[:container_names, :rolling_version_upgrade] -> [:common_parameters, :container_names, :rolling_version_upgrade]
[:helm_repo_name] -> [:deployments, :helm_charts, :helm_repo_name]
...
```
These would be easy to write, specifying where some prior key path should lead in the new config. The problems that come with this approach are numerous: 
1. No easy way to resolve keys that repeat. In the above example the container_names can have many rolling_version_upgrade keys inside of it as part of a YAML sequence. This could be resolved by adding an additional value to the rule, something like `key_repeats = true`. But that would bloat the rules quite a bit and could be hard to understand for future users.
2. Repeat keys must be transformed in the correct order, that is a sequence of container_names must first finish and only then can another sequence of container_names be started. This could only be resolved by detecting the type of container_names as an array and the correctly attempting to parse it which would require some type of recursive/stack approach. This was determined to be quite unreadable.
3. Extracting data from a class like this with a simple key chain requires quite a bit of hacking, such as generating getter functions for all parameters using a macro, additionally we run into return types like Class or Array(Class) which crystals typing system is not fond of.

A simplified approach is to simply hard-code what variable should be assigned where, i.e. `common_params["white_list_container_names"] = @old_config.white_list_container_names.to_s`. This does not look as pretty but the jump from specific solution to a generic one is too vast.


**Transformations**
1. Making use of YAML::Builder methods to construct a String.
This is supposedly the correct approach but it is exceedingly hard to implement as all possible types need to be resolved, this includes the types like Class/Array(Class). The key chains need to be order lexicographically because there is no possibility to move around the keys in String once its been constructed. Additionally there is a lot of prechecking necessary to determine which key chain should be constructed (to avoid empty keys), this gets harder with repeat keys/sequences. Also the YAML::Builder is pretty poorly documented and the solution that would come out of it would be very long, creating a brand new "reverse YAML parser" that is worthy of its own library module should not be within the scope of this ticket.
2. Class to class transformation.
This could be a relatively short solution but it would necessitate that the target class has initializers for passed values, this would make the target class quite bloated (as currently the expected initialize method is through a YAML file). Having a future requirement like this for the users is likely not what we want.
3. Creating a temporary Hash/YAML::Any structure on the go while adding data from the old config. While this is not a pretty solution it allows for some semblence of a generic approach. The ConfigTransformer itself would not need to be rewritten in case of future extension, there would only need to be a pretty hefty transformation class/function that is passed to it. While not the prettiest, it is easily more readable and allows for quick fixes. It also does not impose any requirements on other parts of the codebase.

As things stand the third option is the only one that does not impose on other parts of the codebase and is relatively readable/short. While it does not grant an easy way for future users to transform to a new config, the construction of new transformation rule set should not take too long.

2024-09-05 11:25 UTC, svteb commented
@martin-mat @kosstennbl @barmull ready for review.

2024-09-11 07:44 UTC, kosstennbl requested changes
Good work done on that feature, here's few notes from review:

2024-09-11 07:44 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/transformer/transformation_base.cr
> +      private def hash_to_yaml_any(data : Hash | Array | String | Nil) : YAML::Any
Probably can be renamed as it transforms not only hashes, but also arrays and strings.

2024-09-11 07:44 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/transformer/transformation_base.cr
> +        end
Could be replaced by "case" statement.
case data
when Array
when Hash
else

2024-09-11 07:44 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/transformer/transformation_base.cr
> +      end
Whole function can be rewritten to a case:
Case data
when Nil
  nil
when Hash
  ...
when Array
  ...
else
  data

Also, specifically writing "return" statement wouldn't be needed in this solution.

2024-09-11 07:44 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/transformer/v1_to_v2_transformation.cr
> +          }]
"helm_repository" isn't a mandatory config parameter. It should transform if "helm_chart" parameter exists, and if "helm_repository" is also present - it should fill out "helm_repo_name" and "helm_repo_url"

2024-09-11 07:44 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/transformer/v1_to_v2_transformation.cr
> +          "five_g_parameters" => transform_five_g_parameters
"five_g_parameters" are under common parameters, should be transformed there.

2024-09-11 07:51 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +    end
`enum` only supports integeres.

2024-09-11 07:57 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/transformation_base.cr
> +        end
Unfortunately due to crystals terrible type detection this cannot be a case statement, I've attempted it previously. The `is_a` function does some deeper detection that finds out what the underlying type of `YAML::Any` is.

2024-09-11 07:59 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/transformation_base.cr
> +      end
Similarly to above, this cannot be a case statement, but I will think about removing the `return` as it also strikes me as unnecessary.

2024-09-16 07:57 UTC, closed without merging

2024-09-16 08:18 UTC, kosstennbl commented
Re-created from different branch as #2147