config: Transformer for old version of config
cnti-testcatalog/testsuite pull request #2147
Opened 2024-09-16 07:56 UTC by svteb

## Description
The transformer transforms the old config according to the structure proposed in #2129.

**Notes**
1. To allow for some input validation, the v1 config was reimplemented as class in `config_v1.cr`.
2. Certain arguments are found in cnf-testsuite.yml files spread across the samples and examples that are unused anywhere in the code, these are still parsed but ignored to avoid too much manual intervention in later stages.
3. A new task has been added to allow for transformation, users can execute it by calling this command:

`./cnf-testsuite transform_config OLD_FILE_PATH NEW_FILE_PATH`

4. The `ConfigTransformer` class found in `config_transformer.cr` automatically detects the version of the old config and transforms it to the latest version (currently only v1 -> v2), but allows for future extendibility.
5. Upon determining the version of the old config, the main `transform` function is called which does the actual transformation in code (through use of Hashes and YAML::Any).
6. The `transform` function uses the appropriate transformation rules (`V1ToV2Transformation class` in `v1_to_v2_transformation.cr` file)
7. To make future extension of transformation rules easier, the function `process_data` has been added (`TransformationBase class` in `transformation.cr` file), this function converts the underlying hashes and arrays to the `YAML::Any` type and removes any nil branches so they don't clutter the final output.
8. After the transformation is done the result can be printed to either String or dumped to a file through the `serialize_to_string` and `serialize_to_file` functions.
9. Most edge cases have been resolved through the use of exceptions and their catching, giving users a readable output in case of any errors.

## Issues:
Refs:  #2130

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [x] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [x] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-09-17 21:38 UTC, martin-mat requested changes

2024-09-17 21:38 UTC, martin-mat commented on CNF_TESTSUITE_YML_USAGE.md
> +### Transformer for prior config versions
I'd suggest to use more understandable
"Updating config from older versions"

also consider replacing "transformer" to "updater" across this change as this in my opinion better describes its functionality.

2024-09-17 21:38 UTC, martin-mat commented on CNF_TESTSUITE_YML_USAGE.md
> +New releases may change the format of cnf-testsuite.yml, to quickly update your older configs to latest version use the `transform_config` task.
I'd suggest:
`New releases may change the format of cnf-testsuite.yml. To update your older configs automatically to the latest version, use the 'update_config' task.`

Then: how is the user supposed to know whether this action is needed? Is there any deprecation warning message displayed in  case an old version of the config is used? I think it should be. Such deprecation message should be then mentioned here in the docs.

2024-09-17 21:38 UTC, martin-mat commented on CNF_TESTSUITE_YML_USAGE.md
> +./cnf-testsuite transform_config old_config_path=OLD_CONFIG_PATH new_config_path=NEW_CONFIG_PATH
update_config
and I would also suggest to change
"old_config_path", "new_config path"
to
"input_config" and "output_config"

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/transform_config.cr
> +desc "Converts an old configuration file to the latest version and saves it to the specified location"
`Updates an old configuration file to the latest version and saves it to the specified location`

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/transform_config.cr
> +task "transform_config" do |_, args|
update_config

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/transform_config.cr
> +    stdout_failure ex.message
Not sure what kind of message is printed out here.
If this is an user-targeted error: a clear user-understandable description should be printed out. Is it?
If this is a system-level error: I think then it should be logged to the log channel as a warning/error depending on severity.

Additionally, should the task exit with an error code?

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          stdout_failure "Please check your YAML fields for correctness."
Avoid presonal pronouns

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          stdout_failure "Failed to parse config: #{ex.message}."
operator understandable message -> stdout
developer level message -> log ERROR

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          case @version
better to use hash structures than case.

2024-09-17 21:38 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +        case @version
better to use hash structures than case

2024-09-18 06:54 UTC, svteb commented on CNF_TESTSUITE_YML_USAGE.md
> +New releases may change the format of cnf-testsuite.yml, to quickly update your older configs to latest version use the `transform_config` task.
This is currently out of scope of the ticket, @kosstennbl will implement a check in one of his components where the main parsing happens (in case the version is outdated we will run the ConfigUpdater automatically/tell the user to run it themself), although we have agreed on me providing some method that detects if config is the latest version.

2024-09-18 07:12 UTC, svteb commented on src/tasks/transform_config.cr
> +    stdout_failure ex.message
![image](https://github.com/user-attachments/assets/7952361e-401f-4adc-b13f-1889c9806e04)

This is mostly a programmer-targeted output, a code-induced check if you will. In case of future extension the `case` statements in `ConfigUpdater` methods need to be upgraded. Since there are quite a few, the programmer might miss one of them and this is the way of telling him that he did. The only other way this could be triggered is if the user manually set his config_version field to something unexpected (like v3 right now), in which case it still serves the purpose.

2024-09-18 07:12 UTC, svteb commented on src/tasks/transform_config.cr
> +    stdout_failure "Unexpected error: #{ex.class}"
The ex.class is an artifact of my testing and should be ex.message here.

2024-09-18 07:22 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          rescue ex : Exception
While I understand this, this is such a miniscule block that there really isnt any reason to not just rescue the Exception, but I'll change it to `ArgumentError`.

2024-09-18 07:31 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          stdout_failure "Failed to parse config: #{ex.message}."
Yes, this is message for operators, the ex.message will say something along the lines of "Could not parse x field".

2024-09-18 07:33 UTC, svteb commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          case @version
I will rewrite it, but what is the purpose? We don't exactly shorten the code, readability remains the exact same if not slightly worse, and the speed difference is nil.

2024-09-18 07:50 UTC, svteb commented on CNF_TESTSUITE_YML_USAGE.md
> +### Transformer for prior config versions
I disagree with changing transformer to updater throughout the code, we are changing the entire schema of the config (transforming it), an updater would be an appropriate name if we simply updated the values of the config. There is also the TransformationBase class, changing that to UpdateBase just sounds silly to me. I would be more inclined to call it an Upgrader, but I still think that Transformer is the correct choice.

2024-09-18 08:21 UTC, svteb commented on CNF_TESTSUITE_YML_USAGE.md
> +./cnf-testsuite transform_config old_config_path=OLD_CONFIG_PATH new_config_path=NEW_CONFIG_PATH
Would this be alright?

`
./cnf-testsuite update_config input_config=OLD_CONFIG_PATH output_config=NEW_CONFIG_PATH
`

I am afraid that doing input_config=INPUT_CONFIG, output_config=OUTPUT_CONFIG would not be descriptive enough.

2024-09-18 08:27 UTC, svteb commented on CNF_TESTSUITE_YML_USAGE.md
> +### Transformer for prior config versions
After some thought, we could maybe do a mixed approach, because TransformationBase -> UpdaterBase just does not sit well with me, but other parts would get changed to updater.

2024-09-18 08:41 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          case @version
Code maintainability. For cases when:
- adding a new config version -> add appropriate records to a hash somewhere in the config structure in the beginning of a file, no need to go through all the code and search for all cases where version is considered.
- adding new call dependent on config version somewhere in the code. Then just use a function call from a hash structure instead of constructing additional case command with listing (in future) multiple config versions.

if in doubts we can discuss f2f.

2024-09-18 08:42 UTC, martin-mat commented on src/tasks/utils/cnf_installation/transformer/config_transformer.cr
> +          rescue ex : Exception
Special cases don't jsutify bad habbits :-)

2024-09-18 08:45 UTC, martin-mat commented on CNF_TESTSUITE_YML_USAGE.md
> +### Transformer for prior config versions
Yeah, consider what makes best sense from code architecture/meaning point of view.

2024-09-23 11:42 UTC, kosstennbl approved these changes
LGTM

2024-09-25 16:23 UTC, martin-mat approved these changes
lgtm

2024-09-25 17:31 UTC, Smitholi67 approved these changes
LGTM

2024-09-26 15:08 UTC, merged