config-generator: CNF Installation (2.2) Add generator for v2 config
cnti-testcatalog/testsuite pull request #2148
Opened 2024-09-16 08:16 UTC by kosstennbl

## Description
Create new config generation task, that would generate v2 config.
This task should be more interactable and friendly to new testsuite users.

## Issues:
Refs: https://github.com/cnti-testcatalog/testsuite/issues/2138

Re-created from different branch, old PR: #2142

2024-09-17 21:54 UTC, martin-mat requested changes

2024-09-17 21:54 UTC, martin-mat commented on src/tasks/cnf_setup.cr
> +    config_version: "v2",
I'd suggest not to hardocde "v2" here, rather use the latest version config we have in one of prior changes,

2024-09-17 21:54 UTC, martin-mat commented on src/tasks/cnf_setup.cr
> +  output_file = prompt("Choose output config path (leave empty for ./cnf-testsuite.yml): ")
use CONFIG_FILE instead of "cnf-testsuite.yml"

2024-09-17 21:54 UTC, martin-mat commented on src/tasks/cnf_setup.cr
> +    output_file = "cnf-testsuite.yml"
use CONFIG_FILE instead of "cnf-testsuite.yml"

2024-09-18 08:05 UTC, svteb approved these changes
lgtm

2024-09-27 09:32 UTC, martin-mat approved these changes
lgtm

2024-09-27 15:22 UTC, Smitholi67 approved these changes
LGTM

2024-09-27 16:45 UTC, merged