config: CNF Installation (3) Switch to new config usage
cnti-testcatalog/testsuite pull request #2149
Opened 2024-09-16 13:31 UTC by kosstennbl

## Description
Adapt all usages of config to the new config v2 format.
Remove code that was used by old config, but serves no purpose with new config version.
Update all sample and example configs, use transformer if cnf_setup is called with non-latest version.

## Issues:
Refs: #2135

2024-09-20 08:32 UTC, svteb commented on example-cnfs/nsm/cnf-testsuite.yml
> +  # (kosstennbl) TODO: move helm addoional arguments from name to helm_values
Don't forget to.

2024-09-20 08:32 UTC, svteb commented on sample-cnfs/k8s-multiple-processes/cnf-testsuite.yml
> +    helm_directory: chart
Are we sure about dropping the `rolling_update_test_tag`? Could it be necessary in some test (there are multiple occurrences of this).

2024-09-23 12:11 UTC, kosstennbl commented on CNF_TESTSUITE_YML_USAGE.md
> +Dynamic parameters are not meant to be set up manually. They exist due to limitations of testsuite design.
I wouldn't say incompetent, rather there were some design decisions done by testsuite developers, that are limiting for the features that we want to implement now.

2024-09-23 12:12 UTC, kosstennbl commented on CNF_TESTSUITE_YML_USAGE.md
> +`white_list_container_names: [coredns]`
As yml format supports both ways of defining an array, i would prefer to leave it on one line in documentation with current format

2024-09-23 12:18 UTC, kosstennbl commented on sample-cnfs/k8s-multiple-processes/cnf-testsuite.yml
> +    helm_directory: chart
These config parameters aren't read outside of container_names dictionary in v1 config. No functionality or info should be lost with this removal.

2024-10-01 16:05 UTC, kosstennbl commented
List of changes:

Most of changed *.cr files: adapt to new config (parsing, usage), won't be mentioned below.

- Workflow: use example from current commit, not main. (possibly could be moved out of PR)
- CNF_TESTSUITE_YML_USAGE.md: update docs for CNF config.
- embedded files: add config examples for different versions
- example/sample_cnfs: update to new format via config updater. Some manual modifications where was needed. Removal of some unused parameters.
- setup spec: removal of genereate_config tests as the process is now interactive. Add test for setup of v1 config.
- cnf_manager_spec: remove unneccessary tests.
- cnf_setup: replace generator, small naming changes
- constants: move rolling version tags outside of specific file. (Was planned to be used in config, redesigned later)
- setup: replace config validation task
- cnf_install/config: add updater to parsing, move and adapt some methods from old config
- install_common: remove functions which are not needed anymore
- cnf_manager: remove not needed functions, remove HelmDirectoryMissing exception (was used only as warning)
- config.cr, generate_config.cr: were deleted, fully replaced with v2 versions
- task: redone config generation for platform tests
- compatibility: move constant array to constants, removed validation (now in setup).
- state: redesign elastic_volumes test to not use Helm.kind_exists? (this Helm library method took testsuite config as argument. While writing this comment, i reminded myself of this, want to tear my hair once more)

2024-10-03 09:12 UTC, svteb commented on src/tasks/utils/cnf_installation/config.cr
> +        Log.info { "NOT USING EXPORTED CHART PATH" }
Perhaps a log.for here? The all caps seems a little too expressive here :D.

2024-10-03 09:12 UTC, svteb commented on src/tasks/utils/cnf_installation/config_updater/config_updater.cr
> +require "../config_versions/config_versions.cr"
Is this necessary? They are within the same module.

2024-10-03 09:12 UTC, svteb commented on src/tasks/utils/cnf_installation/config_updater/v1_to_v2_transformation.cr
> +
dtto

2024-10-03 11:44 UTC, kosstennbl commented on sample-cnfs/sample-multi-db-connections-fail/cnf-testsuite.yml
> +  - name: test --set mariadb.primary.persistence.enabled=false --set persistence.enabled=false
It could bring additional problems, which don't seem to be in the scope of this PR, to be resolved later in a different one

2024-10-03 11:44 UTC, kosstennbl commented on sample-cnfs/sample_coredns_protected/cnf-testsuite.yml
> +  - name: coredns --set imageCredentials.registry=https://index.docker.io/v1/ --set imageCredentials.username=$PROTECTED_DOCKERHUB_USERNAME --set imageCredentials.password=$PROTECTED_DOCKERHUB_PASSWO
ditto

2024-10-03 11:45 UTC, kosstennbl commented on spec/workload/state_spec.cr
> +      update_yml("sample-cnfs/sample-local-storage/worker-node-value.yml", "worker_node", "#{schedulable_nodes[0]}")
This test had done changes to cnf-testsuite.yml. With new config format, adding changes to cnf config is not that simple and would require changes to update_yml function.

Solution was adding worker-node-value.yml file to the cnf and changing the value inside that file.

2024-10-03 11:45 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config.cr
> +        Log.info { "NOT USING EXPORTED CHART PATH" }
Was copied from old code, will change.

2024-10-03 11:47 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_updater/config_updater.cr
> +require "../config_versions/config_versions.cr"
Even when they are in the same module, the files still need to be required. This solution was found through multiple rounds of try-testing, and seems acceptable to me.

2024-10-03 11:47 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_updater/v1_to_v2_transformation.cr
> +
ditto

2024-10-03 11:48 UTC, kosstennbl commented on CNF_TESTSUITE_YML_USAGE.md
> +These parameters are needed for RAN, Open5gs and UERANSIM tests
Will reword to "are used for", otherwise - don't see enough reason to separate explanations for this group of config parameters.

2024-10-03 11:50 UTC, kosstennbl commented on CNF_TESTSUITE_YML_USAGE.md
> +The following is a basic working example cnf-testsuite.yml file that can be found in the cnf-testsuite respository: [cnf-testsuite/spec/fixtures/cnf-testsuite-v2-example.yml](https://github.com/cnti-
Will change cnf-testsuite to cnf-testcatalog. Link will be alive as soon as this PR gets to main

2024-10-03 17:12 UTC, martin-mat requested changes

2024-10-03 17:12 UTC, martin-mat commented on src/tasks/utils/cnf_installation/config.cr
> +      helm_chart_path = destination_cnf_dir + "/" + CNFManager.sandbox_helm_directory(working_chart_directory)
use File.join

2024-10-03 17:12 UTC, martin-mat commented on src/tasks/utils/cnf_installation/config.cr
> +      destination_cnf_dir = config.dynamic.destination_cnf_dir
use directly config.dynamic.destination_cnf_dir later in the function

2024-10-03 17:12 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +        CNFInstall::Manifest.manifest_file_list(config.dynamic.destination_cnf_dir + "/" + config.deployments.get_deployment_param(:manifest_directory))
File.join

2024-10-08 07:34 UTC, svteb approved these changes

2024-10-08 11:16 UTC, martin-mat approved these changes
lgtm

2024-10-08 15:09 UTC, collivier approved these changes

2024-10-08 15:18 UTC, merged