Feature: CNF Installation (4) Group several manifest into one file
cnti-testcatalog/testsuite pull request #2150
Opened 2024-09-17 12:41 UTC by barmull

## Description
- Gather all the manifest files from the various CNFs into a single file called common_manifests.yaml
- Modified temp_template.yaml to reference common_manifests.yaml
- Removed code responsible for generating CNF templates as it is no longer used
- Added functionality in cleanup.cr to remove common_manifests.yaml as part of the cleanup process

## Issues:
Refs: #2125 

Re-created from different branch, old PR: #2144

2024-09-24 14:41 UTC, barmull commented on src/tasks/utils/cnf_installation/manifest.cr
> +      File.read(destination_file)
No, it is not needed. I changed logic of method and this left from the previous version. I will remove it.

2024-09-24 14:54 UTC, barmull commented on src/tasks/utils/cnf_installation/manifest.cr
> +    def self.add_manifest_to_file(release_name : String, manifest : String | Tuple(String, String), destination_file = "cnfs/common_manifest.yml")
Also left from the previous version of code. I will remove it. I think in this case it is not necessary.

2024-09-27 14:36 UTC, barmull commented on src/tasks/utils/cnf_installation/manifest.cr
> +          add_manifest_to_file(release_name: release_name, manifest: manifest)
Where do you mean exactly? Because this taking the manifest from ex. cnfs/coredns/manifests. And in this directory are already existing manifests, then it takes that and append it into common_manifest file.

2024-09-30 07:18 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +          add_manifest_to_file(release_name: release_name, manifest: manifest)
I meant as a parameter in add_manifest_to_file, now it's ok

2024-09-30 21:02 UTC, martin-mat requested changes

2024-10-01 08:01 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +          add_manifest_to_file(deployment_name, manifest, COMMON_MANIFEST_FILE_PATH)
That was my request, i consider that add_manifest_to_file should be more generic and wouldn't be so tied to creating common manifest as it would be with default value. 
I think that having destination on every method call would bring more clarity about what is added where.

2024-10-01 08:04 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +        rescue ex : Helm::ManifestGenerationError
Probably begin-rescue block should be only around Helm.generate_manifest, and add_manifest_to_file could have file error handling.

OTOH, it is expected that add_manifest_to_file would be working within testsuite directory, and i think we don't usually handle file errors (apart from non-existing file, which is already covered) in these cases in testsuite.

2024-10-01 08:06 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +    def self.parse_manifest_as_ymls(file_name)
Same as with the add_manifest_to_file, i think it's best not to tie these functions too tightly to processing common manifest, and leave them generic

2024-10-01 08:06 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +    manifest_ymls = CNFInstall::Manifest.parse_manifest_as_ymls(COMMON_MANIFEST_FILE_PATH)
ditto

2024-10-01 08:07 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +    when CNFInstall::InstallMethod::HelmChart, CNFInstall::InstallMethod::HelmDirectory
Yes, it was forgotten, should be fixed with rebase to (3)

2024-10-01 08:15 UTC, kosstennbl commented on src/tasks/cleanup.cr
> +    File.delete(COMMON_MANIFEST_FILE_PATH)
If we would always try to delete non-existing file - it would write warning even for cases, when CNF wasn't installed.

Also, if manifest creation during CNF installation would be unsuccessful, then cleanup of CNF without removal of common manifest seems totally reasonable.

I don't have a strong opinion about this, but maybe these lines should stay as they are

2024-10-01 08:16 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +      install_method = config.dynamic.install_method
In this case, where install_method is used only once - agree, can be used straight from config.

2024-10-01 08:18 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +          exit 1
Agree, can be handled with boolean return value, and exit in sample_setup.

2024-10-01 09:16 UTC, martin-mat commented on src/tasks/cleanup.cr
> +    File.delete(COMMON_MANIFEST_FILE_PATH)
ok, let's leave it here.

2024-10-01 09:33 UTC, martin-mat commented on src/tasks/utils/cnf_installation/manifest.cr
> +          exit 1
also print an user message to stdout in sample_setup

2024-10-03 13:28 UTC, barmull commented on src/tasks/utils/cnf_installation/manifest.cr
> +          exit 1
This is what the user will see:
![image](https://github.com/user-attachments/assets/f3b56a46-def5-46fa-9cb5-68d4c83a0cf2)

2024-10-03 16:38 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +        stdout_failure "Generating manifest was not successfull."
Manifest generation failed

2024-10-03 16:44 UTC, martin-mat commented on src/tasks/utils/cnf_manager.cr
> +        exit 1
Well let it be, we have it on multiple similar cases here.

2024-10-04 09:31 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +          exit 1
stdout_faliure "Manifest generation failed <...>"
Log.for("generate_common_manifest").error { "Helm manifest generation failed, #{ex.message}" }

Change exception message in Helm library

2024-10-04 13:30 UTC, barmull commented on src/tasks/utils/cnf_installation/manifest.cr
> +          exit 1
Already create PR in helm library for changing exception message: https://github.com/cnf-testsuite/helm/pull/5

After the changes the user will see this:
![image](https://github.com/user-attachments/assets/5a2aefb5-940e-43e5-be77-d9aadfc469fc)

2024-10-07 08:57 UTC, kosstennbl commented
Tested, found some mistakes:

common_manifest is not deleted on cnf_cleanup (should be)
doesn't use last helm version in shards (is required for this PR).

2024-10-08 07:47 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +        stdout_failure "Manifest generation failed. Check CNF definition (helm charts, values, manifests etc.)"
manifest **,** etc.

2024-10-08 08:11 UTC, kosstennbl commented
Requires #2149 and #2162 to be merged to pass all tests and be ready for merging

2024-10-21 08:10 UTC, kosstennbl requested changes
Some changes, mostly cosmetic

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +      Log.for("add_namespace_to_resource").info { "Updating resources's namespace in generated manifest" }
```suggestion
      Log.for("add_namespace_to_resource").info { "Updating metadata.namespace field for resources in generated manifest" }
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/manifest.cr
> +      end
```suggestion
      list_of_namespaced_resources = namespaced_resources.split("\n").select { |item| !item.empty? }
      list_of_namespaced_kinds = list_of_namespaced_resources.map do |line|
        line.split(/\s+/).last
      end
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +      sleep(120.seconds)
```suggestion
      sleep(120)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +      sleep(30.seconds)
```suggestion
      sleep(30) 
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/k8s_tshark.cr
> +        sleep(1.seconds)
```suggestion
        sleep(1)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/utils/timeouts.cr
> +    sleep(delay.seconds)
```suggestion
    sleep(delay)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/workload/5g_validator.cr
> +    sleep(60.seconds)
```suggestion
    sleep(60)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/workload/5g_validator.cr
> +        sleep(30.0.seconds)
```suggestion
        sleep(30.0)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/workload/microservice.cr
> +    sleep(10.0.seconds)
```suggestion
    sleep(10.0)
```

2024-10-21 08:10 UTC, kosstennbl commented on src/tasks/workload/microservice.cr
> +              sleep(5.seconds)
```suggestion
              sleep(5)
```

2024-10-21 17:54 UTC, kosstennbl approved these changes
LGTM

2024-10-21 20:30 UTC, martin-mat requested changes

2024-10-21 20:31 UTC, martin-mat commented
remove from "Draft"?

2024-10-23 08:01 UTC, svteb approved these changes
lgtm

2024-10-24 09:28 UTC, collivier approved these changes
lgtm

2024-10-24 09:35 UTC, merged