Feat: Limit cnf_setup to only one CNF
cnti-testcatalog/testsuite pull request #2162
Opened 2024-09-30 08:25 UTC by svteb

## Description
Remove the ability of users to run `cnf-testsuite cnf_setup {../testsuite.yml}` multiple times.

## Issues:
Refs: #2095 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-09-30 08:32 UTC, svteb commented
I have some problems with this one, the main issue is that it would be easiest to implement this change after the rest of the #2120 epic is already done. With #2120 finished we could leverage the ability of setting up multiple CNFs as one, as currently some tests (`/spec/5g/ran_spec.cr`) rely on setting up two CNFs. There is a hack around this, and that is to use the Helm.install function directly, followed up by KubectlClient::Get.resource_wait_for_install, which is not exactly pretty.

2024-10-03 12:52 UTC, kosstennbl requested changes

2024-10-03 12:52 UTC, kosstennbl commented on spec/5g/ran_spec.cr
> +      sleep 5
Is this sleep necessary? cnf_setup should wait for installation in this case and configmaps should be created without any delay

2024-10-03 12:52 UTC, kosstennbl commented on spec/5g/ran_spec.cr
> +  resource_type = "deployment"
Possibly can be removed and used in-place (only used once).

2024-10-03 12:52 UTC, kosstennbl commented on spec/5g/ran_spec.cr
> +  resource_names = [
Can be named 5g_helm_deployment_names for clarity.

2024-10-03 12:52 UTC, kosstennbl commented on spec/setup_spec.cr
> +    ensure
Add cleanup of sample-minimal-cnf for cases, where test fails

2024-10-04 07:57 UTC, svteb commented on spec/5g/ran_spec.cr
> +      sleep 5
Unfortunately, without the sleep I am getting a 50% success ratio, I really do not understand why.

2024-10-07 07:49 UTC, svteb commented on spec/5g/ran_spec.cr
> +  resource_names = [
Crystal variables names cannot start with a number.

2024-10-07 13:21 UTC, kosstennbl approved these changes
LGTM, checks that were canceled are from duplicate workflow

2024-10-08 11:18 UTC, martin-mat approved these changes
lgtm

2024-10-08 15:11 UTC, collivier approved these changes

2024-10-10 18:28 UTC, merged