Feature: CNF Installation (5.1) Test preparation for new installation
cnti-testcatalog/testsuite pull request #2163
Opened 2024-10-03 07:50 UTC by barmull

## Description
- open_metrics and prometheus_traffic - changed config map naming
- ip_addresses - removed

## Issues:
Refs: #2153

2024-10-21 20:47 UTC, martin-mat requested changes
Also add reasoning for removing ip_address to the commit message.

2024-10-21 20:47 UTC, martin-mat commented on tools/curl_install_tester_docker_setup/Dockerfile
> +RUN ./cnf-testsuite ip_addresses cnf-config=./cnf-testsuite.yml verbose ?
I don't understand this changed line.
ip_address is being removed.
So this needs to be replaced by some different logic.

2024-10-22 09:20 UTC, martin-mat commented on tools/curl_install_tester_docker_setup/Dockerfile
> +RUN ./cnf-testsuite ip_addresses cnf-config=./cnf-testsuite.yml verbose ?
replace with helm_chart_valid

2024-10-24 07:42 UTC, kosstennbl approved these changes
LGTM, should be ready to merge after (4), CI checks and approvals

2024-10-24 07:53 UTC, svteb approved these changes
lgtm

2024-10-24 13:27 UTC, martin-mat commented
needs rebase

2024-10-24 14:24 UTC, barmull commented
rebased on main

2024-10-29 07:18 UTC, martin-mat approved these changes
lgtm

2024-10-29 09:45 UTC, collivier approved these changes
lgtm

2024-10-29 11:28 UTC, merged