installation: CNF Installation (8) Transition to new installation
cnti-testcatalog/testsuite pull request #2171
Opened 2024-11-01 09:14 UTC by kosstennbl

## Description
Remove old installation method, use the new one instead.
Change specs accordingly.
Remove unnecessary config parameters.
Fully enable multiple deployments installation.

## Issues:
Refs: #2169

2024-11-14 10:22 UTC, svteb reviewed
As we've discussed in a meeting, I think that rewriting all mentions of cnf_setup/cnf_cleanup internally to install_cnf/uninstall_cnf might be hard to understand for new contributors. Seeing the state of the code I might be more inclined to switch the cnf_setup/cnf_cleanup to cnf_install/cnf_uninstall on the terminal more now, but I am still not sure (@martin-mat we could use your input on this matter). Additionally I do not think that it is necessary to name the methods install_cnf/uninstall_cnf when they are part of CNFInstall module.

2024-11-14 10:22 UTC, svteb commented on src/tasks/utils/cnf_manager.cr
> +    # (kosstennbl) TODO: Redesign this method using new installation.
Let's not forget to write a ticket for this.

2024-11-15 09:09 UTC, kosstennbl commented on src/tasks/utils/cnf_manager.cr
> +    # (kosstennbl) TODO: Redesign this method using new installation.
Done

2024-11-25 08:02 UTC, svteb approved these changes
lgtm

2024-11-27 15:15 UTC, collivier requested changes
blank chars + format

2024-11-27 15:15 UTC, collivier commented on spec/5g/core_spec.cr
> +      result = ShellCmd.cnf_cleanup()
```suggestion
      result = ShellCmd.cnf_cleanup()
```

2024-11-27 15:15 UTC, collivier commented on spec/5g/core_spec.cr
> +      result = ShellCmd.cnf_cleanup()
```suggestion
      result = ShellCmd.cnf_cleanup()
```

2024-11-27 15:15 UTC, collivier commented on spec/5g/core_spec.cr
> +      result = ShellCmd.cnf_cleanup()
```suggestion
      result = ShellCmd.cnf_cleanup()
```

2024-11-27 15:15 UTC, collivier commented on spec/5g/core_spec.cr
> +      result = ShellCmd.cnf_cleanup()
```suggestion
      result = ShellCmd.cnf_cleanup()
```

2024-11-27 15:15 UTC, collivier commented on spec/utils/cnf_manager_spec.cr
> -				begin
please format

2024-11-27 15:15 UTC, collivier commented on spec/utils/utils_spec.cr
> +
```suggestion

```

2024-11-27 15:15 UTC, collivier commented on spec/utils/utils_spec.cr
> +      task_response = CNFManager::Task.single_task_runner(args) do |args, config|
```suggestion
      task_response = CNFManager::Task.single_task_runner(args) do |args, config|
```

2024-11-29 16:28 UTC, kosstennbl commented
Whitespaces and formatting were fixed in mentioned cases, i think that there is still a lot of problems of this type in testsuite, maybe different ticket should be created to fix this.

2024-11-30 16:52 UTC, collivier approved these changes

2024-12-02 08:58 UTC, merged