installation: CNF Installation (7) Verify new installation process
cnti-testcatalog/testsuite pull request #2177
Opened 2024-11-12 13:21 UTC by svteb

## Description
- New setup spec tests were introduced to verify that the installation method from #2161 works as intended.
- Three distinct issues were discovered and resolved:
  * Helm directories with variable depth levels could not be discovered after initialization (resolved through File.basename).
  * Configs that weren't named cnf-testsuite.yml could not be discovered after initialization (resolved by changing the name internally when copying the file).
  * Existence of manifest folder was not checked (resolved by adding an if check).
- Additionally a common point of failure was added with a failure message that was previously not present.
- The issue #2176 was also discovered during attempted deployment of sample-cnfs/sample-elk-stack which was also added in this commit and is to be used in future spec test.

## For reviewers
A lot of new sample cnfs were added to test the new installation method making this commit look quite bloated, when reviewing just ignore whatever files that start with `sample-cnfs`.

## Issues:
Refs: #2168

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-11-12 15:11 UTC, kosstennbl requested changes
Haven't checked the sample CNFs, but i suppose that they should work fine,
Two notes:

2024-11-12 15:11 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/config_versions/config_v2.cr
> +        # end
As multiple deployments aren't ready on regular testcatalog performance, i think that this code should not be commented.
Please uncomment that code and disable (not delete) new spec tests with multiple deployments

2024-11-12 15:11 UTC, kosstennbl commented on src/tasks/utils/cnf_installation/install_common.cr
> +      if !deployment_manager.install()
Maybe storing result of `deployment_manager.install()` in a separate variable before if condition would help with better readability of code.

2024-11-18 13:49 UTC, kosstennbl approved these changes
LGTM,
Dummy-tag specs are preparation for step 8 and are meant to fail.
Validate_config spec is failing because of addition of multiple-deployment CNF for dummy-tag tests whilst multiple deployments are not supported yet for regular functionality of testsuite. So, CI failures are expected and don't point to any actual problems.

2024-11-27 15:28 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_resources.tpl
> +  "small" (dict
```suggestion
  "small" (dict
```

2024-11-27 15:28 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_resources.tpl
> +  "medium" (dict
```suggestion
  "medium" (dict
```

2024-11-27 15:28 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_resources.tpl
> +  "large" (dict
```suggestion
  "large" (dict
```

2024-11-27 15:28 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_resources.tpl
> +  "xlarge" (dict
```suggestion
  "xlarge" (dict
```

2024-11-27 15:28 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_resources.tpl
> +  "2xlarge" (dict
```suggestion
  "2xlarge" (dict
```

2024-11-27 15:29 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_utils.tpl
> +{{- printf "%v" (default "" $value) -}}
```suggestion
{{- printf "%v" (default "" $value) -}}
```

2024-11-27 15:29 UTC, collivier commented on sample-cnfs/sample_multiple_deployments/nginx/charts/common/templates/_utils.tpl
> +{{- printf "%s" $key -}}
```suggestion
{{- printf "%s" $key -}}
```

2024-11-28 14:37 UTC, collivier approved these changes

2024-11-28 14:37 UTC, merged